# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: readarr
    namespace: organizers
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: monitoring
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: monitoring
type: Opaque
stringData:
    READARR__API_KEY: ENC[AES256_GCM,data:IMnSF3LXbtXqkYU0iArkwuFui1ZVPsMP0lIRNKKw9V0=,iv:nLbJv1HE3METyggZnZW4YY7Wdm25mbuWGdqyKW/QJTE=,tag:aEnjNv1t0VGBzvIypGcCJQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArSjNHUWhkOUFCNE9yRnYx
            RUY1eDh5YkNaUXhqWDgvRkNtQnFLeGh6K1RnClpKdlAvN3JUZ3l2VDBaU3R0WGRw
            WVc2N3E1K2VEQk1aaG1YU3NOTjlZRTgKLS0tIElQQ0Vlc0dqZmJvQjZvdjlFdmRh
            dVhJRnBLR1VqVlFmZkhXNVVEWmV0am8KO6ygznT2h5dSQTrK1ykcSFhvlVLdx7Hi
            dauNo3R/r+tn7CwqCRKoEbV/Ko1imkXfUCsbOxGsouQGb0WUUIqE6g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-07T20:44:21Z"
    mac: ENC[AES256_GCM,data:IUm8bSwC3nuewJqDk4d+aC0Z7TdTRDUWhVY8oD1ZDUyQvmDjHZtLMHf5wyhbRyPmrHdzplcU3VYApBcSNCLwPTAHuVAej5ESSYPMjij/fXwbODMg4RJPblD2dUsAoggNXBmO/ciby97m58jA0e5HyExgqFwPZ9sPMbBuVZj0fWI=,iv:Ln56RYe6S38usKPVRusY/1tGBL5GU9R8FNarzy3qZE0=,tag:svnmM2DysTexRkd0gKaBOw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
