# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
    namespace: monitoring
stringData:
    admin-user: ENC[AES256_GCM,data:tQelIAI=,iv:p8253Ow1Jwk+YSIkZFZw34LBjUb79FMOym8PDXTKVZA=,tag:8pjlqtkL21YykpK3s2s4CA==,type:str]
    admin-password: ENC[AES256_GCM,data:DuH20aFgv0c=,iv:VQG8wGIsaM9OlzGKlxZJIiTTfuhW6QBIj/BqeHphoDI=,tag:w46hRJT66Vq+XWvb8lTw2Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOV1hoNFkrbFJZNUdBZ0xG
            amV2MU92bmVZeUlZZ3ovczkrV2MvdGlzNWprCkNkVGVwclhzRXcrMUhNcEowY2lm
            VUJIWlZ3NmtIeVVSL2tlc21qdFhDTWcKLS0tIHYvc2J5S3dSVFRoSUZBKy9sWkxY
            cWlpcWxEZk0xWENRdlBJa2s1Q2Q5OTAK5bLwLr4i5M6K1F1scdKjGtLh0f/wWy4C
            J91NWctuqHCzUGDr0dOW3VA3KOLojWBd+7FkaF2focgKNUPcwiD95Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-06T06:36:22Z"
    mac: ENC[AES256_GCM,data:1GxNyJM3amNd/k4+wAWHYNR9CUxX6QJ0yzCspdW4LLbqFsFVKkPgcxKA6HsfBV4c2McfwEBh/vT0Zg9JdwaF32T3cSCtrgiRzlOZhT7f/h52N6MI2qHvBRetJ4wMjvj4+jnrz/vAudHIQKbgo9Gvq0p0zgOk/RwkyEBlMdL4Q+U=,iv:hHDBf4CbUFXcVoWXUlv4Oeci0CdOXuv39hvjKJh1w20=,tag:QEgUAtawGBivbQFU95dzaA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
kind: Secret
metadata:
    name: grafana
    namespace: monitoring
stringData:
    GF_DATABASE_USER: ENC[AES256_GCM,data:ke47MLdOO/XXSw==,iv:At3sr5ZpWtwi+Me2s+EoWSz7bbqA7GIs4Fq8R15mQDs=,tag:eAKFt4/sFnPVtNK0JLASBA==,type:str]
    GF_DATABASE_PASSWORD: ENC[AES256_GCM,data:abEpGHRNkBKIayekIRlvGAGPFYYfZV4Ot1w=,iv:Zh9B6LWrSvoKc48sNfyXmWLVNPG0vHbbcTVyIgRIczk=,tag:U3z1G5+7a0JYOAjTylPJAA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOV1hoNFkrbFJZNUdBZ0xG
            amV2MU92bmVZeUlZZ3ovczkrV2MvdGlzNWprCkNkVGVwclhzRXcrMUhNcEowY2lm
            VUJIWlZ3NmtIeVVSL2tlc21qdFhDTWcKLS0tIHYvc2J5S3dSVFRoSUZBKy9sWkxY
            cWlpcWxEZk0xWENRdlBJa2s1Q2Q5OTAK5bLwLr4i5M6K1F1scdKjGtLh0f/wWy4C
            J91NWctuqHCzUGDr0dOW3VA3KOLojWBd+7FkaF2focgKNUPcwiD95Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-06T06:36:22Z"
    mac: ENC[AES256_GCM,data:1GxNyJM3amNd/k4+wAWHYNR9CUxX6QJ0yzCspdW4LLbqFsFVKkPgcxKA6HsfBV4c2McfwEBh/vT0Zg9JdwaF32T3cSCtrgiRzlOZhT7f/h52N6MI2qHvBRetJ4wMjvj4+jnrz/vAudHIQKbgo9Gvq0p0zgOk/RwkyEBlMdL4Q+U=,iv:hHDBf4CbUFXcVoWXUlv4Oeci0CdOXuv39hvjKJh1w20=,tag:QEgUAtawGBivbQFU95dzaA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
