# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: readarr-audio
    namespace: organizers
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: monitoring
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: monitoring
type: Opaque
stringData:
    READARR__API_KEY: ENC[AES256_GCM,data:YZMCaINQxIu56a4S0mIuT+aGrvqqUVkCEAXyWYWKQDo=,iv:Edzc9X22BBI2ug+L6JoGON8bSM5m0gzJH/a0fnWIzHE=,tag:X9Nj5/3fsw5iP3JO4rH4VA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKMFdxRkhKbE5EUXFQbTk5
            UFB5MktkYkZielR0VTFNZ3NnYjNUeDhQWlZnCmc2aktsVU53U0MybnJwdW1JNGt6
            Z3RodGRXT0lyUjF2bGI5dmJYQktIVGsKLS0tIGhSYXg2eXoyYWFGL05scHNPOFZ2
            RFNxVTNacW9teFVtODVJSVNlZWc4QUEKJ1JwP4NyCyyCwR4wbRrk/d2L9sizKZzW
            R78hjGlXsirDjND9LCFuprIR26qPHGbnKndwKO0ojCEH2FJkwsWGRg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-14T14:19:41Z"
    mac: ENC[AES256_GCM,data:bEBKLgQvTXKJrSgAIGZOYCiM+Dl5xwThSqC11Y1Xi0CoMpvgnuDObyvcvAfGDwuDuwKxnuCxX89ffUgiVFeNBWuYAvGtsY5M8aP/cXA+08tccnHsQ3mg3NfZesP6/6TeCa4+wOfJVsqiEv1zPAMu3P3MEq3eofyZpo/KL0WHiKo=,iv:kpGSrBfNP9dMPt3NbsMStsEWZT4seL6YufPyO9xmQZE=,tag:MKbl8Cw6L6+Rn5ZKUTajTA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
