apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: loki-chunks-bucket-v1
    namespace: monitoring
stringData:
    BUCKET_NAME: ENC[AES256_GCM,data:BdPdew==,iv:UGxqgyKgV0PyIJ/6fEAJV1pGdAXZzciE7Ex03NkVZG4=,tag:C+G58eR6R4zI2mmWTBVs+A==,type:str]
    BUCKET_HOST: ENC[AES256_GCM,data:PHn4H3/2SfCBl7IYaEFcXR4jwZA=,iv:qNZ+gjqA4EbUrK3whYXB8mcPzKDbls5twyqycc+ULi8=,tag:9nMMQpyyTOHSP/8+aUqziw==,type:str]
    AWS_BUCKET_REGION: ""
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:xyJbzsl8jn6ySEj4r+2iag==,iv:OBgUD5GYyrlZ18TpRN1iblz2jyo27AkXCpvZJkK0JZo=,tag:Dga114JtBjeu/zBLn5IPGQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:Qyxq/BLdaCKrR0X2Txyh9QXNhSL7oZBQSZM2WhV60n8=,iv:7quWt48FJXS3nImqc+75mAoCiw+yAdmVt+O3mPdZX/g=,tag:I9EFG8zyLDm7nShC2S4fmA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0VUdZNE1CcHZtMHZmNTQ1
            QzhhWlg3VUd3RzZYMDA5OEhRZ3A0S2dzb3gwCmhtb21jZmxKWDlxaXpoYU9DNTJV
            RUVjQzh3Mk43MDdJbWFJRDRRQ2EvNVUKLS0tIGYzeDJhaUE0YXRhUisvbDVHeVFN
            eHpBVk5nSWU2SEZFZmkxcEhucndsbkkKqqHoUHlVSz2vxh4Jcs2OTL74lcqbofQ/
            r3c6DmwkTZKXtIz+vJWjTcUt1c5Du4wSO9ZHzkeLDTKugo2Z7YtR1g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-07T18:29:10Z"
    mac: ENC[AES256_GCM,data:Et7FEsFVUIFLhjBsRnkshcYGI5TsscLpOnXGgenPHTfkwK3bXs+P5RbRKfhi08FCmVtzghtxN9M7PPJTNuj2yUibFLzIFXplwl//6cEHz4FPuMBmYZksmP2ud2DtM3i3TXPGkHtPdUyJf8b9rx0cacl/TKGBuczikPaNC/6tS0w=,iv:6P23BwWF462T81OXLyaeHqfcWwexl0xfZmDy4swS2tc=,tag:/6wDNuqrVdl0SZkIGiGtNw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
