# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: sonarr
    namespace: organizers
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: monitoring
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: monitoring
type: Opaque
stringData:
    SONARR__API_KEY: ENC[AES256_GCM,data:lXkrywGbVN0aB4VNA5FDqQL2EeoXs+FfMgdceNsuahg=,iv:Tx5FxsXMwb452PScNOGELV0rbg7lTmknO/gjJhGdgtw=,tag:554vn8Ly/6re6vikA3YhCw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtSEdOYzhFaHNyWVlJaldw
            QnBNUlRLbEt3SFBnN1NnMzZHRnUydkNvT0NjCm0rY2l5VGs4WU1zVnNvS3UwMUdu
            UGtxc1N2V0dDQk1OSFdDd2k1UW5SU0EKLS0tIEJucGtaakMzT3l1SVBiOFpmdC9w
            RUtodDRBMmN5VEFVSnB3VytvOW84ZXMKIMwEUoDhDQzkl33LjJpEAS5W8uzwA6zv
            cNxDRgLocIGI78J5njJeK1yrhFsYKxmmZH/0e7VJBSDtnmMIj6GNlQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-14T14:19:35Z"
    mac: ENC[AES256_GCM,data:DnjDE3+nYLYhCEDImkGVWX7w3kIQ1zPjx3sE8MlXhdlphMeOGuTAFm2Y8LGSXD2Qlw4f2/vzthTdmXEph/ezZCK0fjirVgAt1vHzy22yphA9H8sraUI33/LuOe2RDujOUklfUkfyFDWELPDqSkQHLPjNpFS7OpDzxLCcG7JO14A=,iv:TVVGtwrYEXqRFnsdBWWxn1qJvrWCJtusjOzEm4c8Yoo=,tag:Z+pPc5uCshFR64K7aG92xA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
