---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: netdata-charts
  namespace: flux-system
spec:
  interval: 15m
  url: https://netdata.github.io/helmchart/
  timeout: 3m
