---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: downloads-gateway
  namespace: vpn
spec:
  chart:
    spec:
      chart: pod-gateway
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      version: 5.6.2
  interval: 15m
  values:
    image:
      repository: ghcr.io/k8s-at-home/pod-gateway
      tag: v1.7.0@sha256:ce4871ccdfb98e8dcb5330125a06954ca3b40d9cff3235fb39ac2ba33feff0ff
      pullPolicy: IfNotPresent
    DNS: 172.16.1.1

    additionalContainers:
      gluetun:
        image: qmcgaw/gluetun:v3.32.0
        env:
          - name: VPN_TYPE
            value: wireguard
          - name: VPN_INTERFACE
            value: wg0
          - name: FIREWALL
            value: "off"
          - name: DOT
            value: "off"

        envFrom:
          - secretRef:
              name: vpnconfig  # downloads-gateway-vpnconfig

        securityContext:
          capabilities:
            add:
              - NET_ADMIN

    addons:
      netshoot:
        enabled: true

    podAnnotations:
      configmap.reloader.stakater.com/reload: downloads-gateway-pod-gateway
      secret.reloader.stakater.com/reload: downloads-gateway-vpnconfig

    publicPorts:
      - IP: 10
        hostname: qbittorrent
        ports:
          - port: 50413
            type: udp
          - port: 50413
            type: tcp

    routed_namespaces:
      - downloads
      - organizers

    settings:
      NOT_ROUTED_TO_GATEWAY_CIDRS: 10.0.0.0/8 192.168.0.0/16
      VPN_BLOCK_OTHER_TRAFFIC: true
      VPN_INTERFACE: wg0
      VPN_LOCAL_CIDRS: 10.0.0.0/8 192.168.0.0/16
      VPN_TRAFFIC_PORT: "51820"
      VXLAN_ID: 43
      VXLAN_IP_NETWORK: 172.16.1
      DNS_LOCAL_CIDRS: "local bharris.xyz"

    webhook:
      gatewayAnnotation: setGateway
      gatewayDefault: true
      gatewayLabel: setGateway
      namespaceSelector:
        label: "routed-gateway"
      image:
        repository: ghcr.io/k8s-at-home/gateway-admision-controller
        tag: v3.6.0
