apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: vpnconfig
    namespace: vpn
stringData:
    VPN_SERVICE_PROVIDER: ENC[AES256_GCM,data:2XGUCSbj,iv:VlklkjDvkl1csp/eU0MPF4tyN2ucPwXqOYG42lEfsMQ=,tag:umYXFKRv96IPmElkMZIknQ==,type:str]
    VPN_TYPE: ENC[AES256_GCM,data:VYPt6XkjKjNM,iv:4Ga/SQBXFkzZAMJm2CyTn5Xx32jsZllUH2FWmDPny1M=,tag:d2Y6h1wRnq/4wYQNWZWRSg==,type:str]
    VPN_ENDPOINT_IP: ENC[AES256_GCM,data:AQCZ+RhCyvv544EoPdA=,iv:EnLV4j9nys2aoJtF9QR8H2DXTvtWDYtN8wGuCrY88/s=,tag:iErA/wJj/c1F4ZxxzjBJrg==,type:str]
    VPN_ENDPOINT_PORT: ENC[AES256_GCM,data:QGdAKI4=,iv:6nIZ9TUzB5fUqjglXEmMxlg3HPlhryhETTkRUv63+wU=,tag:+qOJ+5yNaKyUz2oTA5JYXg==,type:str]
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:tpLGHlqIcB8nqzJ7BOvR3Brd8ut5jpOsLhrgtEt/gIQGmtJFC5bXjjyxTYg=,iv:MmSUCA4LCVZ1tU9xUMDcKet/k9yDjjSgdPBp7Ogc3Hc=,tag:EaveDwCxB1g1mnVEGP3ucw==,type:str]
    WIREGUARD_PUBLIC_KEY: ENC[AES256_GCM,data:o3nHGuQMoljzEZv2WYUOztdmBN309Mtessqhqwoyg7K4t8lrfSCQqy8T1j8=,iv:R1my85ac4S1ezi8zCN9eVNvTAgex3zfLuXemSExhx30=,tag:BYxIx32Bg+a3UNFVh39+NA==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:INGOZjW6/8R584o=,iv:75ymG+cKOGIGKBM5A8ihasesq1E3IGfK+04HqnmCWuw=,tag:argbNJXWmKrz78zgqq5QqA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3N25sOE53bHBScXNvOTV0
            eUdXaW5nOWt6N0p5MHF6WUVmTS96NmxVUW5FCnYyNFViUktVU3J5bWNzcVVBMkYv
            SWh1bG1zZi9RbzVYWHZTWnNzZ1RncjQKLS0tIFZ2MkNrejYxbjRTQUNyVHNYQmRM
            NVdrSnVQcEsrUC9vS3ZObEZ6U2l4WXMK11Zwe51KY3wrVO4PkUMkUHcUX5uOhotC
            CDmec5Ax8CePPGvEPThKQYdCG//bERXZkqlKuOuWzrTVWgSaqggNyg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-11T05:54:00Z"
    mac: ENC[AES256_GCM,data:DhTwyonoi5uRLsYgn6SjU0OO3zIwqCoy1NbCTWonLD1cK/5Lfyt7neDr2zp2FK5J5CWFkIbjmMO4PuoJzAHm2G6xL7omTLa5cgD6RpAwrgpkRqNFL/YEj3ZXq3UDvLa/QzPoLcLoxvjOQq6rYFrUxQMVD2LrEyqtLLLBR7xcBjY=,iv:bPqtIYtiBhK5Z5QxXkLPAF5UvprvkrWjOXOcU6nhwEY=,tag:O0mdyz0YArWy9sDuYLF2Gw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
