---  #
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app lidarr
  namespace: organizers
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: app-template
      version: 1.1.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 1m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  dependsOn:
    - name: ingress-nginx
      namespace: nginx
    - name: downloads-gateway
      namespace: vpn
  values:
    image:
      repository: ghcr.io/onedr0p/lidarr-develop
      tag: 1.1.0.2649@sha256:fa286e1271ac7fcd29f25be9b9b3a8170f1e0ad4e12607aa03a3463fdbaca31a
    env:
      TZ: ${TZ}
    envFrom:
      - secretRef:
          name: *app

    service:
      main:
        ports:
          http:
            port: 8686
    metrics:
      enabled: false
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: OnRootMismatch
    persistence:
      config:
        enabled: true
        existingClaim: lidarr-config-v1
      media:
        enabled: true
        type: nfs
        server: ${NFS_SERVER}
        path: ${NFS_MUSIC}
      downloads:
        enabled: true
        type: nfs
        server: ${NFS_SERVER}
        path: ${NFS_DOWNLOAD}
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          auth.home.arpa/enabled: "true"
          hajimari.io/enable: "true"
          hajimari.io/icon: "playlist-music"
          nginx.ingress.kubernetes.io/configuration-snippet: |
            proxy_set_header Accept-Encoding "";
            sub_filter '</head>' '<link rel="stylesheet" type="text/css" href="https://theme-park.${SECRET_PUBLIC_DOMAIN}/css/base/lidarr/hotline.css"></head>';
            sub_filter_once on;
        hosts:
          - host: &host "lidarr.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: "${SECRET_CERT}"
    resources:
      requests:
        cpu: 10m
        memory: 1102M
        ephemeral-storage: "2Gi"
      limits:
        memory: 1428M
        ephemeral-storage: "4Gi"
    podAnnotations:
      backup.velero.io/backup-volumes: config
