---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: thanos
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: thanos
      version: 11.6.6
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation: # perform remediation when helm install fails
      retries: 3
  upgrade:
    remediation: # perform remediation when helm upgrade fails
      retries: 3
      remediateLastFailure: true # remediate the last failure, when no retries remain
    cleanupOnFail: true
  dependsOn:
    - name: kube-prometheus-stack
      namespace: monitoring
  values:
    existingObjstoreSecret: &secret thanos-objstore-secret

    query:
      enabled: true
      replicaLabels:
        - replica

      dnsDiscovery:
        sidecarsService: prometheus-thanos-discovery
        sidecarsNamespace: monitoring

      resources:
        requests:
          cpu: 15m
          memory: 204M
        limits:
          memory: 247M

      ingress:
        enabled: true
        hostname: "thanos-cluster.${SECRET_DOMAIN}"
        ingressClassName: "nginx"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          hajimari.io/enable: "true"
          hajimari.io/icon: "archive-clock"
        tls: true

    queryFrontend:
      enabled: false

    bucketweb:
      enabled: true
      podAnnotations:
        secret.reloader.stakater.com/reload: *secret
      resources:
        requests:
          cpu: 15m
          memory: 64M
        limits:
          memory: 83M

    compactor:
      enabled: true
      persistence:
        enabled: false
      podAnnotations:
        secret.reloader.stakater.com/reload: *secret
      resources:
        requests:
          cpu: 15m
          memory: 183M
        limits:
          memory: 11G

    storegateway:
      enabled: true
      persistence:
        enabled: true
        size: 5Gi
      podAnnotations:
        configmap.reloader.stakater.com/reload: *secret
      resources:
        requests:
          cpu: 15m
          memory: 183M
        limits:
          memory: 11G

    ruler:
      enabled: false

    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
