# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: thanos-objstore-secret
    namespace: monitoring
stringData:
    objstore.yml: ENC[AES256_GCM,data:HarXu+c5wfliSoTVz/wN354kx7MizQHs2saJhacmifG99+lPJ8nE0XajNw9FrhR/d9tEKDx6hAn9MtO6fC81/D1kO4zzRcEoEfL8XdfdzdN9LFNRHP9X72jlSGUPhl4WmjeaJt6WQbsa2v49QrKU9bxhPhZ7wHd88S1TgpOCnB9eLIs7vVDaRT9CIPJsBpIaL1c5yKHX4wPifLzlAYx4UHY=,iv:Vr+uvq+a3wTxyjtCRembZF0bbA/u9P75KqKJPqCCQdA=,tag:bewaGaIaF/+0HrPyod5CFQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzSEhNRUFGRCs0cXJWeXJU
            S0wxOThtem5EYmhSbXNFSE96dTh5SlJHOUdFCldXR0d1dFFYUGFsSVFyRXpKZEh2
            aTFHejNCUE53RkRlcWxGQmgzcWVEWU0KLS0tIHQ5Vy9yL3B6RnlqMnQ3TFFLOUYr
            UHE4Smd0UldCOVltTE1BVEdjRDBlYlUKoRSYxAk28gl3kjt9924LC9fOGu8oPJPq
            fgcCWRSMhNO2tlqaV9VK8i4OSj+2hTNvBuM/oml84T9cuHLkzDskww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-29T01:10:25Z"
    mac: ENC[AES256_GCM,data:SYyfwKv6yFDd6SvWqh39ZMXlN3eIx8OAHeLQzh1D+GcKJupIsYsdgqF1c3hk2kfuYwXFroXD3w26IgFPTQywzgMdcpY5eoyHfySOBzjy/O/TEOLt2UGdPHgfIqYS5NUUnqAgdHRkQa/Fw6JjJT08tieSDveP3m3QajRn273j/s4=,iv:ftT6U88Ltv6LAysouBd8QpHxIFW6u3B3NIb9QWjBqsM=,tag:RUZB3HP2CjVO2JzYvO5C+w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
