apiVersion: v1
kind: Secret
metadata:
    name: minio-creds
    namespace: minio
stringData:
    MINIO_ROOT_USER: ENC[AES256_GCM,data:2Mt5XEAA7a76mmo=,iv:mfx+v0idD9cPTb0fRIpLaMNapaj5dZZ/evODCRkFWa4=,tag:2P3jguLMbAkSFR3SuK7hvg==,type:str]
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:mEufi09cmMPVFg==,iv:gcfSt28QOM8UU3ixAN1VOXWkGP7K4wIn+43ghlKp8lc=,tag:JlXoicmQdVn5vM1vwJhVQg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiN1dGOHZRQTRSck9xT0wr
            M05QVG1sSUdVWWg3Z2huL1F5S3NQUlhsbTNFCmxxSFc5Q1R6cUo2cDBRRHlIc0Jj
            TVYxd1hSaEVuVnQ5UHdXa0FXYkFwbTgKLS0tIGxHamJ0OGc4Qmd6UUNDZkZpSDYz
            d3JnTUNQclg5NC8vTndjL1lVQWhrLzgK5WxztUgnz7cLXh9o7ufz76cIcxaafbHU
            ZG5YITdqUGTCKwPTPC5bbXkz+EeMDIXi3Q4DIinuUhZ/x7OogSBaqA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-09T23:48:33Z"
    mac: ENC[AES256_GCM,data:5HPca2EV8yeRLhoznAZqqugdPXV1CsEishd52014+xe/5DMJ5/uVzGIJOMsG27X0joj91Tk5bVJbzyxrtNi1u2NV3XCprKcsSvCMRiBSZYgctAiazTG6ZhGPxLSxrugyk0zi6NlZgRiGat9piwYwkRl22CKE6Uacg4qs9jt0T9s=,iv:iELZ/mFF1k1T8UyJ5wPlD8mjGfcU9f7IVrYKHL3Xes4=,tag:J4XmRpARBXjGS4YeHd3fGw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
