---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vpa
  namespace: goldilocks
spec:
  interval: 5m
  chart:
    spec:
      chart: vpa
      version: 1.5.0
      sourceRef:
        kind: HelmRepository
        name: goldilocks
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation: # perform remediation when helm install fails
      retries: 3
  upgrade:
    remediation: # perform remediation when helm upgrade fails
      retries: 3
      remediateLastFailure: true # remediate the last failure, when no retries remain
    cleanupOnFail: true
  timeout: 20m
  values:
    recommender:
      enabled: true

      requests:
        cpu: 15m
        memory: 110M
      limits:
        memory: 316M


    updater:
      enabled: false

    admissionController:
      enabled: false

    resources:
      requests:
        cpu: 15m
        memory: 79M
      limits:
        cpu: 15m
        memory: 79M
