---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mylar-varrun
  namespace: organizers
  labels:
    app.kubernetes.io/name: &name mylar
    app.kubernetes.io/instance: *name
spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 10Gi

  storageClassName: longhorn
