# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: whisparr
    namespace: organizers
type: Opaque
stringData:
    WHISPARR__API_KEY: ENC[AES256_GCM,data:O6dHiw+Jcr9+qFtYQ+UuFBaWnxBzT2XuhLel20kk7tM=,iv:RUeVkt93m4zcFZJfiP9eqV1N8RWrikL5E4R5yCbPNiY=,tag:W/3O39pbpFjwIdHL67uofQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYd3p3U3JUb1Fia2FBd0pO
            Y0lPazBCbVNwcGs3eFN0Nkx5Mk9yS0dyS0c0CkpOT0tOdk5XSVhUOFB6cDNpbTBN
            YmZBdEVFRm1NZkxwVkROQWRGMFE2bjgKLS0tIFlOSFdTWTdUL3FIbDFGa2U5OHZ1
            b2F3T0JRNCt1bHBXc1hQaUJ1dWFTbkkK1HiJkyYREM62l5ZPMAcqCuMDeKzxoiGD
            mZLtWrNC5yUaOXqMOHzy9SxFkn2q5LsbDKQQ/B2Tt6/InMg2iq9XEw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-30T04:21:04Z"
    mac: ENC[AES256_GCM,data:uiHHp24F7SQY9wbuWwRqXbUk3F+9fQGRvjvKtnd7gRXxWpBsbRn/Lu7imEKGU5mzlMvzr9WFqfiqJoYWrsk4fTi+otsAAiFv97KlRXrzSySwn69LHi60/ByAvpmQMmT154Qi6d1m4dzqqE5eR0YG1SdXQQPtf+KTHTEd0ZOwKHc=,iv:KadXhjTAGbXMm5LK5yw5btInmR68so+zNvusgkcMKJA=,tag:qevjUrPQuaigL/3ahLkvLQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
