---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app radarr
  namespace: organizers
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.1.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  dependsOn:
    - name: ingress-nginx
      namespace: nginx
    - name: downloads-gateway
      namespace: vpn
  values:
    image:
      repository: ghcr.io/onedr0p/radarr-develop
      tag: 4.3.0.6671@sha256:38661472f781ab30aa0c8c031c3e8314f99eddffd636bd44f2b9b1bc651f684c
    env:
      TZ: "${TZ}"
      RADARR__INSTANCE_NAME: Radarr
      RADARR__PORT: &port 7878
      RADARR__APPLICATION_URL: "https://radarr.${SECRET_DOMAIN}"
      RADARR__LOG_LEVEL: info
    envFrom:
      - secretRef:
          name: *app
    service:
      main:
        ports:
          http:
            port: 7878
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          auth.home.arpa/enabled: "true"
          nginx.ingress.kubernetes.io/configuration-snippet: |
            proxy_set_header Accept-Encoding "";
            sub_filter '</head>' '<link rel="stylesheet" type="text/css" href="https://theme-park.${SECRET_PUBLIC_DOMAIN}/css/base/radarr/hotline.css"></head>';
            sub_filter_once on;
          hajimari.io/enable: "true"
          hajimari.io/icon: "filmstrip"
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: &tls "${SECRET_CERT}"
            hosts:
              - *host
      api:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          auth.home.arpa/enabled: "true"
        hosts:
          - host: *host
            paths:
              - path: /api
                pathType: Prefix
        tls:
          - secretName: *tls
            hosts:
              - *host
    probes:
      liveness:
        enabled: true
        custom: true
        spec:
          exec:
            command:
              - /usr/bin/env
              - bash
              - -c
              - curl --fail localhost:7878/api/v3/system/status?apiKey=`IFS=\> && while
                read -d \< E C; do if [[ $E = "ApiKey" ]]; then echo $C; fi; done < /config/config.xml`
          failureThreshold: 5
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
    podAnnotations:
      backup.velero.io/backup-volumes: config
    persistence:
      config:
        enabled: true
        existingClaim: radarr-config-v1
      media:
        enabled: true
        type: nfs
        server: "${NFS_SERVER}"
        path: ${NFS_MEDIA}
        mountPath: /media
        readOnly: false
      download:
        enabled: true
        type: nfs
        server: "${NFS_SERVER}"
        path: ${NFS_DOWNLOAD}
        mountPath: /download
        readOnly: false

    podSecurityContext:
      supplementalGroups:
        - 1001
        - 100
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: OnRootMismatch
    metrics:
      # -- Enable and configure Exportarr sidecar and Prometheus serviceMonitor.
      # @default -- See values.yaml
      enabled: true
      serviceMonitor:
        interval: 3m
        scrapeTimeout: 1m
        labels: {}
      # -- Enable and configure Prometheus Rules for the chart under this key.
      # @default -- See values.yaml
      prometheusRule:
        enabled: true
        rules:
          - alert: SonarrDown
            annotations:
              description: Sonarr service is down.
              summary: Sonarr is down.
            expr: |
              sonarr_system_status == 0
            for: 5m
            labels:
              severity: critical

    resources:
      requests:
        cpu: 10m
        memory: 1283M
        ephemeral-storage: "2Gi"
      limits:
        memory: 1800M
        ephemeral-storage: "4Gi"
