# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: radarr
    namespace: organizers
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: monitoring
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: monitoring
type: Opaque
stringData:
    RADARR__API_KEY: ENC[AES256_GCM,data:7VUHw66k9pCFAqSXMHuQINzo3gS+6F2+xMxIv11Hu0o=,iv:g+xaaWjEBkjlGu5rGQnDYzHvsiEiNQp3LnRU8GM8Pgs=,tag:72kVyFicw2rbi8thZgdXWA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5WlBuUm9wRXZZZVNOWTdn
            UFkxR3dOdUR4dUVZT1M0QlRKNWFaNXNGTG40CmlHSkFJTTZPbmExbWErT25teU5G
            aFltTzNvZTFPeloyRlBkT1Bvdk5RalEKLS0tIGNxQnk2bExwY2xBMTkxdUZ4T1dI
            dHR1ZTZyM1pRNlFOd2RaTjNuU1I3RlUKuttNWrdNQRPCC2MlvZzJDMmkTUaG6pPI
            KXErOru0VQ3yJuGxw155F6OdgEYT89bVtWcFwSKfSubRK2ySbsoZxA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-07T20:45:33Z"
    mac: ENC[AES256_GCM,data:E7l2zxz6Fn8vYXER2F0Txz1FhphsPrdtrz5Y0opE8JXEfQ8J2/umWce5WtfAvuEoGN0RsR0D6jmZYA/LZJd0xLeZJetyulW1X2AjKz+R7tb71tg7CUzHMFEDZHLaW0kFEBraGo7NYOpEGHUm3uE3GuXEGd3KMmeASGtZw3Kecqg=,iv:fYlG4J5VYVc8kUGRf/rCZVm+T5CG4QdHHNEHi8nMcFU=,tag:HwwuhHl5B1t/SLE7IJJ69A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
