---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
  - ./servicemonitor.yaml
configMapGenerator:
  - name: speedtest-dashboard
    namespace: downloads
    files:
      - speedtest-dashboard.json=https://raw.githubusercontent.com/MiguelNdeCarvalho/speedtest-exporter/main/Dashboard/Speedtest-Exporter.json
generatorOptions:
  disableNameSuffixHash: true
  labels:
    grafana_dashboard: "true"
