---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: &app speedtest-exporter
  namespace: downloads
  labels: &labels
    app.kubernetes.io/instance: *app
    app.kubernetes.io/name: *app
spec:
  selector:
    matchLabels:
      <<: *labels
  endpoints:
    - port: metrics
      interval: 5m
      scrapeTimeout: 1m
      path: /metrics
