# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloud-credentials
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:BtGexmNegLTap18j4V2Nbw==,iv:RyLaJ9yMMo5DKs0H1rtojohLq3Ey4+J+Dfr9pTLsgNU=,tag:A+7RWQKgkX/qPWLgiWT29A==,type:str]
    api-key: ENC[AES256_GCM,data:CccR3pyO2ecTt+acqScIZGPf8cNmAGh6hjbnjzdQrDb2e48NBw==,iv:4l1hbCRrxsQnvjcy2vBa0rY8o97IjLV0XuwVGXRCHp4=,tag:DS3KzFNUpUD+22MxFQFTWw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDM1dGdkNISVNpYndtalhm
            bk54K2VRdjhzM241RmtCWlJKZG84N2YrT3pjClhuRjlzYjN6dmx6YUtSRkdNSlRm
            enlNQ0laUDFwZXJXcTFrR29mWXBJUGMKLS0tIGdrRllsM3BVcFozczhRaU8wblFr
            aG1uaU1vcnUxai9YQjFJRjBPdllTdEkKt5aARAjiTkUldMuQ+Qd1g3L6Yy7fPbz5
            tFyKm/Puu/+EuPG52kB6Hw0L6qv/+xjfCmrPDIQIPs8fCoPpytRX4Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-26T16:56:20Z"
    mac: ENC[AES256_GCM,data:OmjMYNCOiIZBy9bQI1tzALEWBvW5lKfTvnV8ISEf5S5Kb7mAxeAfOwh6E6mCuhVWcgljf4cQbyAahswEkoyWl2tq8S/Rg3iEdP/vxo+xaCIk4Mfq1+6B6El+DONuQQVM4oUnC8gt06Alue/8w5qLbAwfmLvfKUwz5Pysj8GGJl0=,iv:PcbHw3NKPykvRuhVpV0eXnYVPS2mMQstRkCWB1740Dw=,tag:XDxE21Olt3oBOFwHAUQAjg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
