---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
driver: nfs.csi.k8s.io
metadata:
  annotations:
    velero.io/csi-volumesnapshot-class: "true"
    snapshot.storage.kubernetes.io/is-default-class: "true"
  name: csi-nfs-snapclass
deletionPolicy: Retain
