# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:20Bmb1Uw8ybFtEY=,iv:mdV7eDBgM9p1w3SSyrrl1mpLagtVH58nFNouDw0uwWc=,tag:RlU3rduzLYltyP0hT0UkcA==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:b9UnxyJ2exHnhWRLl549VA==,iv:VE/gBPcyYOsOkR8Vo7HUvKD/G+wcqUjCmpGatEwtrYs=,tag:qhrKaWQZrSyWUk/mv58TWQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0R01EcUNvV1BOK0dJSE5o
            L29sWnhEQWMwclJLbStIVEJkWnMwV3VwSEY4ClhldUp2azR4NUNSTU1wcThxeUlj
            TmlQUFpBcUd2T0habXZDaWtkUEp2NXcKLS0tIGhxaWsvV0thOENuK3U5K2NQSCtk
            d3FrVUt6bzRCQkZVMU5BdFZjV0RKMGMK0GppN2xycBxBYr8zEW6ti7lKFVcRtNj1
            jhCJqb+6SDmrlE1NimwCx54+hFR0PCYtvO/RHtVX2cSn+l6KWzvpWQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-26T16:56:20Z"
    mac: ENC[AES256_GCM,data:7+5T9mS/fiYFUvrYM7xADB8f0s3DOFIYEp7fLY8YGXPuH+j00ZpvKoUtuPHcYvNnMrB5rVHmq7jektYX+PMHdDUA4uWEmNOwe3f2WCt17BnwzarS/fd9rCvkm+4Uyv9VeGAroqnUZqV5xPFW+1Q++/UujtP2QbhdD0n3xqy5BcM=,iv:IJsA3UurBTNnEEnqWWQ9rkk7xwf3JlORVJZpZIeZiwU=,tag:b/ULwcyZP2moyXu4l4v65g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
