# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:GIUNxGCsdkoPggI=,iv:58ZWMjMs2mhsjM/GA5AmCf+6NFhtd3deDJDMCKTWTdo=,tag:/7q9VPCoe6H3NGDeFdgbWQ==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:mQAu0e+P0FFNPirJQDhWbg==,iv:FzH2rVC7fY1DM5c1ssZN3Wlo7Ip70aUo5UF/3ROMEeE=,tag:P2m/7v+sR19SSkqt3MjA3w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKV01GakhhNjhtMnpLVWgr
            K2haSkxnR3RXakxCSTQxKzIrTkxlTGtKNlhJCnlua0xPazBRdlFtWTlpUWtKcDlR
            VjhCSG5FV1E2VWpsdTNwaG5DVW0zSzQKLS0tIG1uQmZVTU1oUjlpN05kZTQ5am8y
            NFhpSFFjMEorOEhvODhSaVNydytJMzgKhuCPrV3T0mkA75oaGz300loUcMyqNaZq
            KGiO/f3SryiWxuYpy25pt6a4Dp+lo5xncuqO54mSB60thOhj9t1CDQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-04T06:55:09Z"
    mac: ENC[AES256_GCM,data:hP/lkQ+mu2ryVxN5EewGNGap69UDKnBxjBE3hX0P5HMvwNnoMyaq5uzsnHxNvfGol+lEMTso3Uf4lxjSpzeAxgKd1IkjeNNGBuzmQ783Oj+7n+//Nx/2l+CdQQfV+ydDQ5/Ku8HqQGLjqZqi4f7Fy3r2WWB3kkKLhOPk8iiGv4o=,iv:SriqgOeq439p6xX4ubP241L2OYWzzAe32hYECKRp2I0=,tag:J76ciZSt1ngBMYWK4h19mg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
