# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: ""
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/secret-reflection-auto-namespaces: ""
stringData:
    SECRET_DOMAIN_LOCAL: ENC[AES256_GCM,data:JkB8DOeDry10OHE2,iv:L+qfQ5TRizZZ4NkEII8AC2y5Qk8iKbMGLTodobHYjfY=,tag:QJROtIYfrudFh+YQg/1eXA==,type:str]
    SECRET_DOMAIN_CC: ENC[AES256_GCM,data:G1j0m0mU4+LwnA==,iv:kZelj3uWkEhOxxvGbHi2dx3U6aCyRS5y6qgBmc89B44=,tag:pZcyo0/1v5dbRIy8WGLKAA==,type:str]
    SECRET_DOMAIN_CO: ENC[AES256_GCM,data:260/UuIm9fbsHg==,iv:KPkk5f9CSFQGcBZnGmTI6XCIukaBP4sdAJM+wOubaM4=,tag:jHvPycfoRAdKOT93Rg8M0A==,type:str]
    SECRET_DOMAIN_TV: ENC[AES256_GCM,data:kyAQ9MhQZ8HPHQ==,iv:960TGHixMJWjER2i3DEJfkIiXDfD45cGPTMRtVxF/xQ=,tag:LEzlXrZlK0SPtpu5AlL1Pw==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:CmkA6AEj3+2d/No=,iv:ZSl47oAwWA0AYI1U7wzzqP+spNLcZt4pCbIq7MwNMxY=,tag:++TM3HWAfgls1XoaB8JcLg==,type:str]
    AUTHELIA_SENDER: ENC[AES256_GCM,data:s+r4iZA9kwTNeSa0kSHrQFqGsp1+G66WnNto,iv:AZWLn+mAUZuwf806lRWBQPa+OcwJ7UOkUY6+xA7hnkQ=,tag:KZ/7UoEFIp+JFrDGinveYA==,type:str]
    SMTP_USER: ENC[AES256_GCM,data:/zz7JFnxzAWG8O1pCo3XGg==,iv:MAP6rcnLUoyyGnHxrUPCVd46patZEkW4awf2fDZqZjo=,tag:+SQuy9s5vvJxXQbm+41n2Q==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:rOUg5s3lMg+Y8nQliBulWQ==,iv:/lNnHjEd70gTMe2N/IQ+hkNwNzCjqYoFlJM+iqjqnJM=,tag:M8fY9xnF2Vr/KSsguHeAZg==,type:str]
    SECRET_CERT: ENC[AES256_GCM,data:iTeG7wvyGVZ6o4OulM/MQXsm3xfUNTHrElAHHn8p7L7LZigZ/N6USx/m,iv:TIgHKdfZsLaFgX4QXRV9x+YishcTAFAXfcTpPcaqjVQ=,tag:CM1JjmgdujD9CF4tvEBnAg==,type:str]
    TZ: ENC[AES256_GCM,data:DnGYpeWjZ2wBXKtjfr6Vftyt94o=,iv:PNOXpDjKQreaWJeW9Fb6bSQLVA61ZycQ7yKT21YuHcc=,tag:1A4uUHEpnCvYivLsHXlLxA==,type:str]
    NFS_SERVER: ENC[AES256_GCM,data:fYMH0KcTaV9Jvxw=,iv:LZKubCj6I1jLXPYJchSC3MJFkK00SkCREr99mj78ffw=,tag:ubfraz2t5IYa+J+JIIokFg==,type:str]
    NFS_DOWNLOAD: ENC[AES256_GCM,data:HhpuinTCqHNbqIwJE4z/42c=,iv:w8lk7cwzJUw4gubUcnW3dJBIsCE7hj+EsmbF2A8hERw=,tag:C8ip6lvZaqg3Xbh0ilGFDg==,type:str]
    NFS_MUSIC: ENC[AES256_GCM,data:m9EhWqNoMBcv8F4UXQs=,iv:H0/ePGOGY1FhmR0WqFIknHsw+XrYZdBW+/O0Wf3JiUk=,tag:ySNpCsZaLfOi5HzqjToTOg==,type:str]
    NFS_MEDIA: ENC[AES256_GCM,data:gmG6wwooa6WmbPEuctg=,iv:1oeLAOK2DbS6H4ITqR7lTWvBLFl9oixU2A6GuHOATOM=,tag:9yAHGeUJeFLhTwPKcLCJQQ==,type:str]
    NFS_BOOKS: ENC[AES256_GCM,data:jsVu547ivc+Ubm9zlLk=,iv:2dnpEBKs9mOTB/OWQuXecj+Rf6xOZt2QxlRD29q+u8g=,tag:54kbiydFUy3jLsi+Jppdkg==,type:str]
    NFS_KUBERNETES: ENC[AES256_GCM,data:92PT+xxAjZPq8lioynG/Gu/LEA==,iv:3Z8KzjHUq1VW9mbp12aUwZSKefgG6xIh3XDw2MuBvEA=,tag:qsAs+jp6W0Qij6vEc2Un+Q==,type:str]
    NFS_CSI_VOL: ENC[AES256_GCM,data:PXATjZe8CgJujaAGj5ogBuQeaw==,iv:mDQyP7lgS5Sg/VUGGHpYCm7JS83ksaGpN0+/TvR6Tn8=,tag:K4t+VdN1gzk4Cre/65o5KA==,type:str]
    NFS_SUBDIR_VOL: ENC[AES256_GCM,data:TsTGz9OHlaGj7GIRQxpdHiMlkdOB0YQ=,iv:3f+Hft15nl9x6p6B6lTz1ANLzGlV0CdkCVDHe+poNXk=,tag:W2oMjNBwbRsWkNciPxqGmg==,type:str]
    EMAIL: ENC[AES256_GCM,data:msg0UB6cOtnWmfla+9sZ9g==,iv:B9aOH+dX6yn3sW+30HYrfT+n3Zuw5GYdF7M2d0mF8SM=,tag:xCC8kIxoX6bTiMiBcnVCoA==,type:str]
    HTPASSWD: ENC[AES256_GCM,data:KcA/Rhh4NezEh9wiDiyNtwlErdVFX5KXWS04a3OGzxYsqFnP2x3XEV/evcRpHiIYgT7FDSzuFftVax2Wy2seP1Z/,iv:gQGWBu7OM7J8xtYdvQPf1L3bxRSE99uiN+3YbRWcoUY=,tag:w5XNs3XdxMnapBe7F95A6g==,type:str]
    TRAEFIK_IP: ENC[AES256_GCM,data:MrQE2fOSdzD991o=,iv:4Kmb38PZf1CQw1splQ05fbmnkQGEQYqBCZz5QPLU/Jg=,tag:3DZ1Lv5Gedyf83jowXexCA==,type:str]
    LONGHORN_BACKUP: ENC[AES256_GCM,data:1/y6wH//hlbOKwFdJVukABZAowgKc5+dcZ92XQNlEFRITls=,iv:X5cU9AlUsNCHt+swGfBSd7XFMvo6y7Kk7aTkkFZ0DOc=,tag:vSfrsatb/HEyZIbw1vFIWw==,type:str]
    NFS_FIREFLY: ENC[AES256_GCM,data:C489/3GZmkJFwxkolYE7Pg==,iv:8hCu6tZAYrny1t034nlU5LJfOrKsDckX59C862uSet4=,tag:BJUKEURxjCPecMK6kOAYhQ==,type:str]
    NETWORK_K8S_CLUSTER_CIDR: ENC[AES256_GCM,data:ODxDghvYJTk/0Uep,iv:FoO9LKhgyavJNIf4JWL9JI4lJq7kb/epdhpZ/lWgIPM=,tag:eBq8m+PFU1BExFGBJvFveg==,type:str]
    NETWORK_K8S_SERVICE_CIDR: ENC[AES256_GCM,data:NYqnCBd/1MJ6vb0G,iv:T3biTXSpUA1tJYx09jZf5e+FQMQp0kAcaEY34vayEE4=,tag:JcweimCZ/rWUJ4JL3KQyCA==,type:str]
    SECRET_WIREGUARD_PORT: ENC[AES256_GCM,data:PbGK9is=,iv:rnF1p7rlw9Kua7Xmbu+a43DK728MiHujtdERBkyC8RM=,tag:kl27kzUrIDoExn2WBgnUgw==,type:str]
    NETWORK_SERVER_CIDR: ENC[AES256_GCM,data:6S6d5HQwgPgDQg==,iv:yIXh7DfTAIMg8Jvvi14R+LM6+hkNYq/U20haJ4kwkuk=,tag:cmZihZINw6ADROBZ5nG83g==,type:str]
    WORKSTATION_CIDR: ENC[AES256_GCM,data:191/AO43WBgSY4KSgDk=,iv:67DGKmXDWSEOVMcD+Yczdl+mL7zTbTyaHu/lTSVrjVU=,tag:RSTnJiKSLMayaM5EBihxIw==,type:str]
    SECRET_PASSWORD: ENC[AES256_GCM,data:mWIxz3OS08E=,iv:vwAwkC+eyu8t63l6xO++ml9G7EEk+Ab6whSvLqAyIRU=,tag:If/ETx2+BpNGC9utqKVe3g==,type:str]
    SECRET_QB_USERNAME: ENC[AES256_GCM,data:237olMA=,iv:uqdaR5mTKTMO1eTZbJ9d7a15y4b5qCi9vHzurD/AbEE=,tag:wFrfV/0Eg4YCB0LMW3qSlg==,type:str]
    SECRET_QB_PASSWORD: ENC[AES256_GCM,data:/Q7u6IjeUhk=,iv:iOcf6pSBhTh+onHy+9Ik0RQPz8tUF7yKGEKUPuvRToY=,tag:XPRrGvmKaooWmPq4KFRw+g==,type:str]
    NFS_MINIO: ENC[AES256_GCM,data:HNn5wRu5arKrhyM83VA=,iv:akUwL4WmEOMPGNjASH9t17cqFw0NOxHaj6ouLyhOUzg=,tag:PwvCMBAlombE+/80YOtw6w==,type:str]
    SECRET_MARIADB_ROOT_PASSWORD: ENC[AES256_GCM,data:EAxceNFmd5A=,iv:W/lKbsuje56GiIiNZ3nhLZPKKcAqulSElisslEvlgUs=,tag:x/UH0RwYms+6Lcsl24MR/A==,type:str]
    SECRET_POSTGRESQL_ROOT_PASSWORD: ENC[AES256_GCM,data:Qmy6od6ihAM=,iv:dEo0t5DCiSaacqZ1oS5n/9RWOy92ZSNOVfzZv5UGWUg=,tag:dNbKnf4pJITNyRYJdBK+DQ==,type:str]
    SECRET_KOPIA_PASSWORD: ENC[AES256_GCM,data:pRpUDvXdfX8=,iv:3upjHpwq+hlQLvP6rK9PzwPIhgTH/7ZwtDttGl178GE=,tag:Gk0owzdHYZghGnCQV1dsqA==,type:str]
    SECRET_BOOKSTACK_DATABASE_PASSWORD: ENC[AES256_GCM,data:JARZu6YvVcA=,iv:RdFZC/3y71+w4WxTVU3S+1htLVXbGpaTcRRICR5BzC4=,tag:ag9iZuXmpswQH5olbZF5cw==,type:str]
    SECRET_VIKUNJA_POSTGRES_PASSWORD: ENC[AES256_GCM,data:9n94jYAgZ/k=,iv:vsK6BMDvf3udiyEOTc/YNkrJsudL+MvBxCM+2Ed3tw0=,tag:GAqgAaQDgXEhuTpivC3QHQ==,type:str]
    SECRET_VIKUNJA_POSTGRES_ADMIN_PASSWORD: ENC[AES256_GCM,data:mufcOoNfYrM=,iv:Nl4QhsS6z0wCTf3wPWwuJ3OU2e6VZj8kP2AFcLlN/Ho=,tag:hjMVlOSGSbPKsSivyPLHgw==,type:str]
    SECRET_VIKUNJA_DATABASE_PASSWORD: ENC[AES256_GCM,data:H97Yg07G1g4=,iv:XOFAJVPImpIl41C9scnGdVdYlbbmn+Pb0AZyfCIJfHs=,tag:11yoYd9PzFgzwUfLNCrWfQ==,type:str]
    SECRET_VIKUNJA_JWT_SECRET: ENC[AES256_GCM,data:qjDtSQjTAjA=,iv:1yIs8P2vjhrI8O3PYqVU1ZGjHHkNz/vawk7KGSA2yWM=,tag:V9vJr+s9q5DismyciVdMFQ==,type:str]
    SECRET_RANCHER_ADMIN_PASSWORD: ENC[AES256_GCM,data:LzezQi5Uv7k=,iv:t4PozrZvaT4oGZTADlp7G6296Qxwiwcw3pVAmOzmpvA=,tag:4us9oYQkEWzGq/6XMDkljw==,type:str]
    INFLUXDB_ADMIN_USER: ENC[AES256_GCM,data:5go8No8=,iv:y4bzbLL+/KjybSS4diWi64SNBzGhZl4PXisbxWUy++Y=,tag:pc5vNsLzMLHkH1TFouyfcQ==,type:str]
    INFLUXDB_ADMIN_USER_PASSWORD: ENC[AES256_GCM,data:LyvUjkLyx70=,iv:zflRG2IkdKExwmktk/6WqgtQmwvHk2ZbmnFX58yXTKA=,tag:vgAdw1jftvS1FMmtjTVHxQ==,type:str]
    INFLUXDB_ADMIN_USER_TOKEN: ENC[AES256_GCM,data:CQcCNJ9ovkPpTQ==,iv:Vufa5HsbVfK+iWLJzKNJ4YU3L/4WTJxtoqOqGSbtM+I=,tag:pSrkVWK2QscfN/0mnKmYAA==,type:str]
    SABNZBD_API: ENC[AES256_GCM,data:LYLSUpJfh3/DLBPzvna067U5oJ4CvVL0GOyZ8zk1XIY=,iv:tCzyz+CmalgnvFLbp6Rm5iopMYwdwZqf9QEvXcqLdm0=,tag:VOnArPSHG9pu1RfsI1iwXg==,type:str]
    PGADMIN_EMAIL: ENC[AES256_GCM,data:ozNg76biECYtnHQ9X7c09g==,iv:hyd2jTaNHk1oMcBSrSHU2hFQOBNH6I7ISGgRMmSS3Mk=,tag:kp2w1vI9m9a78b8S+4UdvQ==,type:str]
    PGADMIN_PASSWORD: ENC[AES256_GCM,data:vacBnOramZ0=,iv:CIDNyc5gb1/qPFA8dDqOvSCBYf7cAMQS+DRW7o7rIWQ=,tag:SYdKYDMpgco3g4LNpzhxAg==,type:str]
    AUTHENTIK_POSTGRES_PASSWORD: ENC[AES256_GCM,data:q1Dwof34pdgOV4Yp73dE,iv:lmeW/IUTE38JlulCQl2uptCNXBGSP2A/fgwt4LgHZnI=,tag:Q/1bV2uFHP+9KZfZ3ihqwA==,type:str]
    AUTHENTIK_ACCESS_KEY: ENC[AES256_GCM,data:JimV5Jnj5UC8ylEduZ/zvA==,iv:xmC1TT47zAPC6hsFLeKvNGGpIRc2D+QB3I/ih2eDBYM=,tag:UAehN4WvN6rwH0DngYIfng==,type:str]
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:BYIh3hw9NieISNU74tluKSuDQUoFkf7Fz89w4SbZLZw=,iv:oX8pnyHsM7mFH1i96t8hqeAw6GRHU75jhDks5AshaY8=,tag:lzbq+qtyhI7enhTfzPtZdQ==,type:str]
    AUTHENTIK_BUKCET: ENC[AES256_GCM,data:XeZPty4TQ/40,iv:nZjtP50vLW4iKmY2jo8pFcT5hyrxzodtLcEhQT7aFMQ=,tag:FvLIH6JnEMpI/bQUt1i5Gw==,type:str]
    SECRET_GRAFANA_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:W5j3UE6RhtM/XAsIcXhB8iIqesaY7j0mMI4=,iv:JgYv3MyjkZ37dnFsdlrB2nSFu15W7Yy+5gjkEv1kbKw=,tag:8QI964CzbQEx05GC5m6Rig==,type:str]
    AUTHELIA_SMTP_PASS: ENC[AES256_GCM,data:aDRSNw/Oofh0VNJKIoT2XQ==,iv:6sj6/V06AqoMS3ghclU75R8dNupOqfCj5SBFxoCCgiE=,tag:GUzjgmZfMbEhjBFDSVnenA==,type:str]
    SECRET_PUBLIC_DOMAIN: ENC[AES256_GCM,data:0W4FS0PS8m9vZyQ=,iv:IsGdEACT/o5W5B/eikBInuqJzdllBZ/ROAs03gYEgNQ=,tag:3o8q5iyQcnoQ6NYDQKlysw==,type:str]
    SECRET_OUTLINE_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:ttedHZQOx37ZKx1EgrUXmuIjjXcvGYa/KL0=,iv:ba22HmB0Yck0xFy3bP87kAkGiVA7NtPVblGEBlU9M9w=,tag:fCTG4lpqqmkshvrDalGoDg==,type:str]
    OUTLINE_POSTGRES_PASS: ENC[AES256_GCM,data:A1Ng1huij3HUUQWbQVxTUYYrFnhQZx2YfaQ=,iv:s1A+ydk1PQnftozGDWapuh9zNNb95LCPGdPXSMPHEwU=,tag:WEa8BeuB5CoR2a43ZZFJww==,type:str]
    OUTLINE_POSTGRES_USER: ENC[AES256_GCM,data:OS+RgDg89Q==,iv:9WbCCg8SMGvR5QWogYg7521foZ+7lvTD9wgKsot0FpQ=,tag:it5oj3l7bI5I37WqJrQDTA==,type:str]
    SECRET_GITEA_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:EtSN/guQQHc63qtpbZFxXq78dPBDtZxNYII=,iv:vANHzErPFjECFAATWKpdAJPJOs5HMyKjMxfV66n4UeE=,tag:ymXzwxetlABeraWAoL983w==,type:str]
    SECRET_CLOUDFLARE_TUNNEL: ENC[AES256_GCM,data:71HTO63GEZ1IEwf/cKx2oYbpboqdMrrcm7iEnmJPN0ceOKEHEH/ZqRhGC1b5oA61QVQyfUA=,iv:l69AFCJN1Eb6faZRWymrC+/2snn/8hzJGs+zTn287ZQ=,tag:c/L1mizmkjwZ2VXvVGZbug==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3djhKZzgvZmkxWDBBdS9Y
            MDJrb0FqenFOSElpeDJqNWUyd3doNm0xK3hzCnZuZ3ArRmdkNlR3bXk0QzZkY1ln
            VHdKQUVnbmx3OHZ4NzF5Q2hUa3lsWTgKLS0tIGpZanJxdkc1NmxDc1dSUjNLM29U
            L2hIMVBUQ04vd0hVUncxZlBxdkczQVkK5pmzY/i63V1AP0jwDzgtVR5s395YKQ+t
            InT6B+fJv+stWAUHkMREloQw0sfY/eX2bTsBrN3Uf/rR7ldaYuO2Mg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-29T03:17:11Z"
    mac: ENC[AES256_GCM,data:ZSXi1kHfdsPbDm9X46HOU5MmoN7iEffRpeGteJ5MJ+hV0OvsWbO1rOi+782ONZPWUTG8hLWeiyOG1xz8fRG5sGYQY4ti2nPeJFXK5Wq4QJhHWTrk6IjnCJtUGiLOpthXnCgchjXFbbzZNG/bRi/AXMF+g6ZbSklI/LKW4C7JI4U=,iv:nm66e4o6iYEjAfCFCKdPboa5Z4rHnf/oVPrHOAfLzY0=,tag:mdmR3KHFV3idNX+eBOKUYg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
