# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: ""
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/secret-reflection-auto-namespaces: ""
stringData:
    SECRET_DOMAIN_LOCAL: ENC[AES256_GCM,data:a+Xd+hc/c7ymJsqW,iv:1owaWPyQwjfSTmmrS6BPTeBGz4M3mCBYu0esqB0xv7c=,tag:H+d10FV4RwVKvnC61SwY1w==,type:str]
    SECRET_DOMAIN_CC: ENC[AES256_GCM,data:dsWo4JFhBEhioQ==,iv:Jn8kfz0oz6l5viTFRrvW0FTxN+7BZHFl+D3tWSAjzdU=,tag:nCpVaVUg66jgP+/Cn6oXSA==,type:str]
    SECRET_DOMAIN_CO: ENC[AES256_GCM,data:ut5oJVY8TWQibw==,iv:7B8hSRDz9hqL3Eg4xrnECe0o2PNmgvTs9kkVvctqn9Y=,tag:D/4O6zGk8VdnbWkXdHH4Xg==,type:str]
    SECRET_DOMAIN_TV: ENC[AES256_GCM,data:MPV+26bsM6pkOQ==,iv:auy1+Bdscnh2EdApz49oA+6QQxYWYaJl7YghqxcIpUk=,tag:cGYctg6/wAO2l3BS6cpIFg==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:CWLcUngQy66jpR8=,iv:R0ksWpVM0oeej1lDmfc1XhO5AnALKCN+N+W3VQGd89Y=,tag:uV7GKoYMxCT70DFNV3MBoQ==,type:str]
    AUTHELIA_SENDER: ENC[AES256_GCM,data:oQOQiSHg45NxtnJaynLTAGhcH839nV65F9XP,iv:KDpDfvbRtZab/aDakuIc/lG6TsrBNBxeEeL0VZbYBog=,tag:A0qQ8we979ZGItEIGvCCtQ==,type:str]
    SMTP_USER: ENC[AES256_GCM,data:8y5qHBg3RcCtjXzgf7wLjw==,iv:9AKnKFU+iPD+K5wq5sSdPa7y6kkMZuzgrDsLMMHpaYo=,tag:gBjpC/FlsVe5N3eKzJjy/Q==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:3IJg42FcQH5bXl7j3in5Jg==,iv:I3j1D76mUxwYlWFYcrBVtawsvwhS9QOTf0U3LusNUgA=,tag:Af3ix9yJ8lQQFcU95lcGKw==,type:str]
    SECRET_CERT: ENC[AES256_GCM,data:gD5CBG6JJZ0AeD/BEPKYJm1+4/UXGzZCKLJhyYW31AJdA/5Zz6I58T34,iv:MxFleY/vu2tmGRymu58bChZNtXTBCGA/EAvcrKJojRs=,tag:1Sp4bNTXCWwdN0tCFyYW8w==,type:str]
    TZ: ENC[AES256_GCM,data:Xz079szlJQiLjzdkBjp61uccvbk=,iv:QTOOVeBGMe33FaLKwvR/ST2/lEBm+Y1m4yOmJzViv3s=,tag:elyhZZOdV3EQr8hoRTCL7g==,type:str]
    NFS_SERVER: ENC[AES256_GCM,data:2V7DUEG80nPaZLg=,iv:Lt1yBDPghuiwWa017HHvKPffjso0c0SFdXv9KSWKwOM=,tag:GXL+yKHQk+LfZCx7QgNzPA==,type:str]
    NFS_DOWNLOAD: ENC[AES256_GCM,data:ps0E2RsEqpVPTZ/aXOLrzds=,iv:DoIRW1+zKjnaJ8OYSUpZf3Y4A2tZ0YdGVM5X0eQoKyo=,tag:2P3FNhKpH39l7dqLzni7Vw==,type:str]
    NFS_MUSIC: ENC[AES256_GCM,data:bZtiMam7GrLgTJrxMsA=,iv:xjZ0OsbncV8ilMJOb9aNVm00kVi+rC/jZW89yjdvBeI=,tag:+pHHmao0aIPY44V23b1m+Q==,type:str]
    NFS_MEDIA: ENC[AES256_GCM,data:tHIeTV2pIgyw9CiO6K0=,iv:kTXKb1Uf0aW0Y6pu23/xO1WumXqPz5sfUAlBU3PnsuA=,tag:x4JJ0Z3715HaXH3//gHOfg==,type:str]
    NFS_BOOKS: ENC[AES256_GCM,data:qfYyjvcJNgA+NrNRPjs=,iv:RoGHUuN2XoijSTkZ9INH3WRaySwjHwRGdiz80ccXXns=,tag:nlqFFSyzFf2mwoQ5QCdf5A==,type:str]
    NFS_KUBERNETES: ENC[AES256_GCM,data:hC2gJ81GuQNzrUxYbc7TdBZE5g==,iv:J3DQlXxCuk/i+P3T8Vo9pOUnu/MS822Kawr9qpPI0HE=,tag:WaX5UtcXiJElNqGCYzUZfA==,type:str]
    NFS_CSI_VOL: ENC[AES256_GCM,data:sL9DttB8IynAMyk1hU31LiDFng==,iv:ragN/ZGKWdQVUQcUcpUvxLbcPql5M4oDIogOyKDAwkY=,tag:lgkKUtECzlozeGisWk9xJQ==,type:str]
    NFS_SUBDIR_VOL: ENC[AES256_GCM,data:fdQbQN2UD+f2sK6XKkz/jxdFlLm9VTE=,iv:rULHc6ZAQ7GVAICI3vgJPaUZ2pG/NNDvfnL4/WY36u0=,tag:REcZnDkiFCC5kclEBeWw8Q==,type:str]
    EMAIL: ENC[AES256_GCM,data:5eazqB0mHSWegVsJuOJNKA==,iv:5mR8+EgTHJW4a/1is0GxEF2gmdVQti7Q0gEdKDGMP5w=,tag:Cu+c49gw6oRHtxrQWM+YvA==,type:str]
    HTPASSWD: ENC[AES256_GCM,data:dvshleqE6fEqg96QA2cwH66l79wvuNcoR927mq39VERR8aKP3/ornwSSPstBc2j7nP3ySWEDGf2RxZyJYdeACivn,iv:azA47/d+57+S9snEdpOHXu4JmRwa2jrhvOE6s9IlMFg=,tag:fZfNvqfUawDTa0vRMdnn7w==,type:str]
    TRAEFIK_IP: ENC[AES256_GCM,data:n5pq/f5c5DJ0CBc=,iv:iCR7bxooXL2Lh89E2dyKHY1vPtiWHlnfCWe6LwtuULc=,tag:Pl/HWIkz6BJpOvQT2Huakg==,type:str]
    LONGHORN_BACKUP: ENC[AES256_GCM,data:TAEEx6Hn+DCAEYnSy8MPi9iR9OL73cEq/I3Gr2utnBp/SmI=,iv:eiLxEzuFFCnRlWs0CuYqKd06yx31zoofMqEP7hR9Vlw=,tag:WM98dfBwrlYZWFD/nif1VQ==,type:str]
    NFS_FIREFLY: ENC[AES256_GCM,data:PPjNumdSU+y/H0AX+YEdFg==,iv:/m3UPJZ0wgldyTuTHwiAtCP4nvghUjajGVemsVISqLU=,tag:3fHA3/vjGn6398RzmQMR2A==,type:str]
    NETWORK_K8S_CLUSTER_CIDR: ENC[AES256_GCM,data:09csXJRWxNT4MHa2,iv:km8jhD3SwIG3J3tjz8Fkzo8d6l0wuXIvSCq1csNDBGc=,tag:6ggu2/HX+eAWc1iAHpV4wA==,type:str]
    NETWORK_K8S_SERVICE_CIDR: ENC[AES256_GCM,data:Ydyz63MsPv3UDfoj,iv:7fPD706B7P7wlIv/fNlBfqKZzkgHvQwBGmCLhksZLms=,tag:OQmE+E8Tj7jAQWpp1zlZUQ==,type:str]
    SECRET_WIREGUARD_PORT: ENC[AES256_GCM,data:VGcmKHo=,iv:10zQqS8veS6CKZDBkiFzCg0ptSyk92JbAqVGxbRrbsw=,tag:/6ykZOVMbCbeR9IG5YHPnQ==,type:str]
    NETWORK_SERVER_CIDR: ENC[AES256_GCM,data:VzhQZcuEjOQYVg==,iv:OoAvTDssj7MXKFKOGY0rt8V1xbopBzXLWOCodx6cbtc=,tag:ox5T1k5Cs7gN2MkNjxqB3w==,type:str]
    WORKSTATION_CIDR: ENC[AES256_GCM,data:XUlFDe3d+JTeVWfKppE=,iv:+Uc0wyP98BN9cNC/Q08mkOQzM/cQ8T1uzVw0tAPPS50=,tag:8fbT3LPKEzPSx4mszXpEIw==,type:str]
    SECRET_PASSWORD: ENC[AES256_GCM,data:ol5sdw8KNTk=,iv:NvS4aHmlBKnxQtryUm7NJczl35udwJs1L2yn8txOJVY=,tag:grxTHW6agPRLKpgY2d6bnQ==,type:str]
    SECRET_QB_USERNAME: ENC[AES256_GCM,data:RTsloMY=,iv:hf2aB1z8zI7jjgSKiSnW5LubX0drBs+acz7jDrXKAx4=,tag:ma+T8qxV0+mOt8qLOhXfZg==,type:str]
    SECRET_QB_PASSWORD: ENC[AES256_GCM,data:FzaJMTooJrM=,iv:pf0ZlI2eMEKPjcn3onME9/9ta+SVW5/WEwCv2zbb0t8=,tag:LF/zPlKMpR1RnBPGrS/NTw==,type:str]
    NFS_MINIO: ENC[AES256_GCM,data:WO+OOoP8mzktS6WYtWI=,iv:1SynvrLq9GqrcBuLkIR2CZtQAqCTmDY9qYD8hStXCGA=,tag:HSTP18Z5/Fw1HJUxvi5qXw==,type:str]
    SECRET_MARIADB_ROOT_PASSWORD: ENC[AES256_GCM,data:kdJwd1KkJLs=,iv:urzSaxn3n8s4fowzQ/BS3JD5qGLl7YpBL+ZpufLO4tg=,tag:TaKvBJLh4gGLPzo3dpaVfA==,type:str]
    SECRET_POSTGRESQL_ROOT_PASSWORD: ENC[AES256_GCM,data:rVtMMWwGArw=,iv:9QJFXVIo/3yLRz7yKkprJ9iBv/fQZMjHvsu3Wpi5/yg=,tag:E5d7oGf1u7CPaaxoXHOxYQ==,type:str]
    SECRET_KOPIA_PASSWORD: ENC[AES256_GCM,data:5KL+Yw9DcoQ=,iv:njA/GxDgesCeJREwlkhtwFhgOacVbPEkgLwVXlIhipI=,tag:1PHCeOpq8YUcQOu4CoCkog==,type:str]
    SECRET_BOOKSTACK_DATABASE_PASSWORD: ENC[AES256_GCM,data:OkglpEtSnOg=,iv:MpZyodzKyncJwuTDS4P7zCZ8Q/MUGwT5s1+oU7t6/FA=,tag:/SE/tOBh8OtJq7o9QpjH9Q==,type:str]
    SECRET_VIKUNJA_POSTGRES_PASSWORD: ENC[AES256_GCM,data:2Poz4B7ZZt0=,iv:OfqvEKbx5xrRhA2r75useD5hKVLl4/+GF86ODDC3We4=,tag:lBpULdBz0lDpX5p7CVBMQQ==,type:str]
    SECRET_VIKUNJA_POSTGRES_ADMIN_PASSWORD: ENC[AES256_GCM,data:LEw9VDtmETQ=,iv:cyjbeKY0eSiXeduaAv0B3ybVCgaTD8tWE+3UVrZKQHo=,tag:va9fIIDHozy997de61L+sw==,type:str]
    SECRET_VIKUNJA_DATABASE_PASSWORD: ENC[AES256_GCM,data:ASPbA8rzmvE=,iv:4vz6cEXctYmcqNG+rDk1FrPYaJNejgk22BQmqosVQIw=,tag:xt8ekXOoZjO67/f3ErkQTg==,type:str]
    SECRET_VIKUNJA_JWT_SECRET: ENC[AES256_GCM,data:OihfDMRipIs=,iv:OPOYuATe1ZdU2usNLZKtmHnA7MURClaq3xxii2sMLnc=,tag:YUTXy50yYGGj9VJWCkcnJA==,type:str]
    SECRET_RANCHER_ADMIN_PASSWORD: ENC[AES256_GCM,data:6aD5+6GwApQ=,iv:EOkAyIprG7/apoiAxNDd6CSuR1c9EmXIrA54S0GtnzE=,tag:TRjHezoUp2R5RtEIZWW6Ow==,type:str]
    INFLUXDB_ADMIN_USER: ENC[AES256_GCM,data:9U4Zd34=,iv:5C+6etxPYdChd+ZorkfLQ7vmu7Hakl2oIna4pwhECnU=,tag:tn3UyrwatJHYymHJ1sp/OQ==,type:str]
    INFLUXDB_ADMIN_USER_PASSWORD: ENC[AES256_GCM,data:SunTX3ZMZ2s=,iv:krLpchBQe4X9lJB+wb039gTlx5aziMdEY1rwwriowyY=,tag:yfz/Xv0xutitc1kapYNRcg==,type:str]
    INFLUXDB_ADMIN_USER_TOKEN: ENC[AES256_GCM,data:w9CfOchBhgNBGg==,iv:6VflWcuEHExjd41hWqVve9vzN1J/UeD8Q1XLsMqVLd4=,tag:HcnQcF6t22GHv6pdzNHuMQ==,type:str]
    SABNZBD_API: ENC[AES256_GCM,data:HkI3lxPYYyMb0GNAhsmS/iOKY2qcjkR397s+Uaay2hg=,iv:0nqe1UygaREiyYrLYFuepSN/oskuY+n25jDRWs5DOEE=,tag:PR61KAlMiGmJFpKafG7zRw==,type:str]
    PGADMIN_EMAIL: ENC[AES256_GCM,data:OJ/noCxi1gzAKWuRKj5i4A==,iv:JpIq3nCwVFABJacXz4iilOZA+d2RjNjRlZP5R+YR7/g=,tag:MKhw162RKy+NbZMLGejF9A==,type:str]
    PGADMIN_PASSWORD: ENC[AES256_GCM,data:xlwHOlwHpy4=,iv:sKzKyB4B/UVCRpLpI3W5vszOLbpIUsPTMIEyHgiE+a8=,tag:jZAcwOCOyttvSEkxmRptxw==,type:str]
    AUTHENTIK_POSTGRES_PASSWORD: ENC[AES256_GCM,data:JwpBuIWd0ncjD+dAGgI1,iv:jJ5Z//B6N0c0z5DpCsTOUJ2ccm2WWx4NFNkugMbsO8k=,tag:m9It3vtPCsduyBzeOLrjHg==,type:str]
    AUTHENTIK_ACCESS_KEY: ENC[AES256_GCM,data:vZL3uGHdpmazFLkd5mrbTg==,iv:FMs3j5/yGaBYWlOm6xZR4/ph7iVsNZ31fGJuR2FfJJ0=,tag:i4wBUCDTD2Y5InDZQxE+Fw==,type:str]
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:AwlHcwJbjyKXXhflFpW4y6WPYCfiFXJtqAOOE319sMk=,iv:5txVcchFUznkNAjNLnnaB1b7GYslUCzTRwyaqeBCX2o=,tag:GV9qr6qpcQ1fVNgC2qQxOA==,type:str]
    AUTHENTIK_BUKCET: ENC[AES256_GCM,data:4ljDyngFHMbs,iv:LlxgYZJkeY7hBtfylA6X68GNlraynNEDsmYPpDkL1jE=,tag:z9OEtigp0LWD+/QtOIzrZw==,type:str]
    SECRET_GRAFANA_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:GcridTH4NZczPu5nJzvtH7Wn9iGRk6OMRS0=,iv:46txe5qjmQKqj/uD4mpF3bEGFngnU/0huPpZ8Iz1aCo=,tag:LvOqoZ7pgp3HWN9QEQ7IbA==,type:str]
    AUTHELIA_SMTP_PASS: ENC[AES256_GCM,data:t0p90HnMvFNqe4ZzlyIDvA==,iv:V3jZ7UaRklRMsd+9n3dAfeMtq1v15mmU+N7Lm2HlHgQ=,tag:1A3wr/A+XNTla9w0LSEWZQ==,type:str]
    SECRET_PUBLIC_DOMAIN: ENC[AES256_GCM,data:W7hEAZQAGzVUizA=,iv:uTwWRJPsrA00xvQAcRNzPO0oV7gI1yvgbhM4UUoinUk=,tag:soODpVEctPO4St2xiRo5iQ==,type:str]
    SECRET_OUTLINE_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:1EM4t4DHHPDua0aCS5ACjMmGDGeueLufysI=,iv:rKkngQUOiLGHr9TR2WWtrQo5ufroR7EfNTciyPqKTzw=,tag:0F4erc5ek1LeE7CMXIjUzg==,type:str]
    OUTLINE_POSTGRES_PASS: ENC[AES256_GCM,data:KGXlDR0QW/+xJAIhvfSxRHhbx68NxZIq9J4=,iv:+ZtmFvgl0Ukasq1hjwSa5M3JTRatFPXmi6yLyDbsr+o=,tag:4R4dtKxqE6tyJj/2fcnWRQ==,type:str]
    OUTLINE_POSTGRES_USER: ENC[AES256_GCM,data:WlwlCkLZdQ==,iv:V8cClJSjLKVquL4Gpyjg2kbqyp2H/+Sz3qUEXfPKRU0=,tag:Jk/DBXPem6vxrNbmisVbwg==,type:str]
    SECRET_GITEA_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:hOjgsK5GaFagipJ99k0qMiQMGHtuZAvJoIU=,iv:opVuUam3aaloKkXDeCLOjXI1f1ojyi7MNv+vThCzZUI=,tag:0gSxME4pYJ8jFP9ckZ7Y3Q==,type:str]
    SECRET_CLOUDFLARE_TUNNEL: ENC[AES256_GCM,data:UUqd5zeten8K6RGTGcggR1d/VB505TQvHFW2SBPPiAR3mGpUC3srAOeFDRivzr8qhZzMhpk=,iv:5i0rEmJ+hzutGVUJKFEgKYo3EPYOoU1fU0Mn0IYtCeo=,tag:9HpeIPurfAUns5vo8U8FJw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxUmdHSlRpS3NMQlN5WHdX
            VjFDQVczZkdOVHdiQWR5TENOcUhXK212WWxrCm15bmdRMFVCeGVBRUxQNXNJUW12
            SytHN3A1L1ZZWDJNREp6M0RGaEdHZ1EKLS0tIHlHQ043WUF5VzBleEtIUGNsbzlp
            K0g3NU5nL25jT2YzZHVxTTdaR1VZUG8Ko2uk9BtW/n9+I1dJbu2SvXABmTgwrpQu
            z4jEDwJ1QPaubrmo3F0vXBwmjBkrDwNf9G0hjJSjtzWQ1nA/KA7Z5w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-04T08:37:31Z"
    mac: ENC[AES256_GCM,data:cT4+siZnrPDcAd1znrTpPSlvxZ2JTRMbyNG7ChhlCCGA+Bnr1JsxSNHHk1wilIjgEenlT4502JICoxhrzdorXZb62V7OklWGbAO1IslsSyHAxDPOwHnEmud/zn3mU+Lh70m1xdv2ArXQD6Ap8RlMfMzinbyBzHqN3iRWP7W/nHA=,iv:H3o0YekkYbihsViDYF+hVXp64cjhxLnk9cxelVTygn4=,tag:ps1tnj0GO1EtnFT12sNlMg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
