# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: ""
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/secret-reflection-auto-namespaces: ""
stringData:
    SECRET_DOMAIN_LOCAL: ENC[AES256_GCM,data:zAVKJHHASp1bWgHY,iv:DaWV+XCkxyNy8kIk7zgJFEjg+LZN87ZeJCwoMeGawSM=,tag:oTQHVCrqtesGR6LCWnrVLQ==,type:str]
    SECRET_DOMAIN_CC: ENC[AES256_GCM,data:poOJYJtkmWqEKA==,iv:l59BrIhdH0P6aK7egGbpaHX+own2EIIE0eV8nAN212A=,tag:3RSbE05VIgJDgoZoGoF1qg==,type:str]
    SECRET_DOMAIN_CO: ENC[AES256_GCM,data:LnKtdEby4q/oPg==,iv:AiXEziJlrEuAWs7oHnE9UlfSiUvYw9hd2q1JIflI5SQ=,tag:gN2YswLJUNyX8/FL/jzc9Q==,type:str]
    SECRET_DOMAIN_TV: ENC[AES256_GCM,data:08vh8CfD8Wr2Sw==,iv:jmbaz/7Vd+oKwtMkWs8g+O04AJvVIxtAp40kGuVclGw=,tag:RcALwW4IkQxlke8uXjFefg==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:DJ53sTg17f1UcbA=,iv:Z/UpKKldEuJQbqHYL/PCj2mNIzRDRviD1cKmPc74wGo=,tag:RnGJ411ig4wvhjw+uBAIcg==,type:str]
    AUTHELIA_SENDER: ENC[AES256_GCM,data:joWMIEGEeZhE2yiIvpqvxAayRscyuvEWcj0g,iv:NbuJwQc85WCQRAHYUD77CGLlRMTe6LNjZ1xyu7hVUrg=,tag:j+vL9725g6jIURpkks/y+w==,type:str]
    SMTP_USER: ENC[AES256_GCM,data:ZxQ47MREdLbNYgXKcGRtew==,iv:mDJjNTKLRavbL+llAApCTRcDuocJ1Jm6sHOdWvI/d+8=,tag:4mcYycvX5Wrxc5nCn5Hd+A==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:rWrcd16hd4hxGgl3+rEa8Q==,iv:iaKZedbefVS34FnQOAAE05XlU3aeLKDNj/CRTcOBX78=,tag:VdENTEPY4Lm/9RXHgr5BiA==,type:str]
    SECRET_CERT: ENC[AES256_GCM,data:JPp7DrUF2KFyXwxggoK1mpDPyvK2kMXP5kXKa1onqBumXh638ou5wR31,iv:AJHsps3hYFWqWXck/72nhojATrYfi6bj+ZDVnFyrqRY=,tag:OP4wd1jYidnrmiJQT8E9dw==,type:str]
    TZ: ENC[AES256_GCM,data:3GqsfdVAR6Bu6wmlC+JZx/wqWq0=,iv:wSAaN0Vgg4+nszm2w63swm9ZvFyQh4zgwQ2ZsHCNhuY=,tag:/DWnb+4+DjUgfabfuLO9QQ==,type:str]
    NFS_SERVER: ENC[AES256_GCM,data:tSxB2SuGY9Jrhek=,iv:pRYioyNbGtF/o6Oy9pekvrP1AAAhpomDmXnP02/m5Vg=,tag:2aJ5SS7RI1KL1s9FLo2Y6w==,type:str]
    NFS_DOWNLOAD: ENC[AES256_GCM,data:zg07g1nxWakbOZpboiZ4DQA=,iv:mRTQTcbcHdQe7FGD1If0REkAoLW49qOKvfD+DnHMmsk=,tag:SGlRE+VvUAe7YfupQOdiLg==,type:str]
    NFS_MUSIC: ENC[AES256_GCM,data:kN+QJuSZup7Q3MhIRAw=,iv:Tn4TEK7EBAyk0B7bHhqvmNjw041dbtIx10UipO213ZU=,tag:sI+DU4ZZw+WrBjCA9Jck3A==,type:str]
    NFS_MEDIA: ENC[AES256_GCM,data:+TOouiTTN7B1vQVcJnA=,iv:FmgjgDn7HKAgD/QdCmUb5Oe4sZOoa5nv2Jdpd4rUieU=,tag:Gs7xU8StCJ5pKNwSK8bLSw==,type:str]
    NFS_BOOKS: ENC[AES256_GCM,data:EuW9vnWeRT48eFalKxo=,iv:CD9L3jSFBlNV4jlz/ho64i8QZe00TJChu7Xnzk1oAcU=,tag:YXw/VlqHTxuQVRK/VLNl9w==,type:str]
    NFS_KUBERNETES: ENC[AES256_GCM,data:DcX4HPllmTXKD+6QYu9YSjIHpw==,iv:BPOpzxsn+Zuirkd0qovcfO8QjQFLKI+gAywMpFPeK7c=,tag:NsXnaimW3aVKBegTdGp3mQ==,type:str]
    NFS_CSI_VOL: ENC[AES256_GCM,data:tleaXpqehDxVMNbZmbHzyQozkQ==,iv:P1zO4LVr1urwhj/7++4/oaRzfPfjvGkD15hq+jOmI0w=,tag:WzPPvmB1ek5GgpaIp0Ldkg==,type:str]
    NFS_SUBDIR_VOL: ENC[AES256_GCM,data:ctevygFHDRBofJxmm9OyRgiGCDQxWuc=,iv:mN+Bn0YkFROVTmbne6PzqArBqcaYAXpKFunfYlkjlH8=,tag:y8POqfjROhg6vvqoyueV7A==,type:str]
    EMAIL: ENC[AES256_GCM,data:TVVtKgwJ5Vsd59dA7+XB/Q==,iv:N6NAU6jR0/ttaPRqValOW4M3VA8zGrwuXa459o9GMF0=,tag:IL5HYbolsc+OJB4wR/KxZA==,type:str]
    HTPASSWD: ENC[AES256_GCM,data:lVMXyJjdo+Qx1mjQ8sVT7iGoFh3slSHw7E8CwKsqUAa/06JSaLtBZGLnr+wi5v5VMQD4OKhg8h0vsyj41K5YLcZt,iv:wFAoseCFFNKuiZ63BGH5BvdsSNqbVm5l+oSBxCnXdOI=,tag:mYDwtMc8M0+wYzSQTjDQsg==,type:str]
    TRAEFIK_IP: ENC[AES256_GCM,data:sK/xnMlRyBLQrG4=,iv:uzrf03c8EKBCz2YKAJeBqHBbk2dZsdUgveQu6Td3hfI=,tag:sNdkerv/IEvhSPL1EmY1fw==,type:str]
    LONGHORN_BACKUP: ENC[AES256_GCM,data:4kgVwtNu5FvFEnT93hoTdscbs31N3I6fCMafphV4XmPAzxM=,iv:j+7xFIsGFdCzkVdaFvcTos1EM7+gZxuRB2h31Lp5Jl4=,tag:jYzg69hY59VqwZQWhjOp0g==,type:str]
    NFS_FIREFLY: ENC[AES256_GCM,data:qDWBZNQDlUa3fjd4+TCKIA==,iv:ggXoHXBNoS2qZHDCNNotRE/dzjx3IvpdZurNyh0d05c=,tag:77ViXLVdyCy4K6FaoPqrFQ==,type:str]
    NETWORK_K8S_CLUSTER_CIDR: ENC[AES256_GCM,data:OG0rxW97RLDbjcYd,iv:7gVOsFKCyxjd669x7I/umr8e6pXfpGlgNgqqepU6HM0=,tag:idQjG3YllaHQZLcYIf5F8A==,type:str]
    NETWORK_K8S_SERVICE_CIDR: ENC[AES256_GCM,data:so/XFF+8NUHVy02Q,iv:eV0ODjCCSiY+3E51LJGIid8tECmwkCLqBnjK3tsYUFE=,tag:0qCmVysmQnjvnS0cg1qlyQ==,type:str]
    SECRET_WIREGUARD_PORT: ENC[AES256_GCM,data:ljdMNSY=,iv:uhSEKQ5NnTYSYzqsD66B+ThFEjEGAEE7KEIkTX0KOXM=,tag:ra/tcE0LRN9cvKACOlvt7Q==,type:str]
    NETWORK_SERVER_CIDR: ENC[AES256_GCM,data:JeLXMD+k9H58EA==,iv:yJzCF4QUVlYywggdybRAWenB2XKxUZEaLumC6ctpFM4=,tag:eEz3PziZGdlR1QXMlh9yeg==,type:str]
    WORKSTATION_CIDR: ENC[AES256_GCM,data:w9luvBf36Y5oSlNKfhQ=,iv:Gk/Qor9+7LEB0Vt3KUQw5BjqPXLMRmEX3XbkQYjfcF8=,tag:bNguj4+n5iXNUkHHZNmrbQ==,type:str]
    SECRET_PASSWORD: ENC[AES256_GCM,data:Z8G3g2l8y04=,iv:OCE2yIQzoxaN6RK6NiNZO70s1+6sk8C66OAK9ebh5l4=,tag:kEQiRSBJ300affzMgppM2Q==,type:str]
    SECRET_QB_USERNAME: ENC[AES256_GCM,data:56lS5B0=,iv:pCOXdIakw/58PrCuu9eeEorpB6zIF6IWG4MpaeQ6oZU=,tag:gH7nKsBt4Gb2888wSfbqdA==,type:str]
    SECRET_QB_PASSWORD: ENC[AES256_GCM,data:niU5UxUfupc=,iv:4IdWBQL3DQFwPCkt5V5mkeU1ivJnbWQpAB3Df1L6bNA=,tag:d1s0jykU/c/VHFokFSZQjQ==,type:str]
    NFS_MINIO: ENC[AES256_GCM,data:GN4k6cigjlYjF//q1dg=,iv:pJ06RPeJYnHta+XFSZq8yiD2eFos7Y60Whjw0/SAfRk=,tag:WVaNIPWXe9SwSijbo+Gqsw==,type:str]
    SECRET_MARIADB_ROOT_PASSWORD: ENC[AES256_GCM,data:PYzkjWV1MT4=,iv:JRXXpu0ORDDnp2MKrIaYSAd6gJNl/9BUTlQ8luGbaDw=,tag:PUgiisas6niGjrQEtGQQYQ==,type:str]
    SECRET_POSTGRESQL_ROOT_PASSWORD: ENC[AES256_GCM,data:R2XwNHNb84g=,iv:LzbxEQX1Pd4O1/0CR6kbJETMS5xV2NAKVw55xFPPtQc=,tag:vUjMOYItSy5UnAYh/8pYcA==,type:str]
    SECRET_KOPIA_PASSWORD: ENC[AES256_GCM,data:TrWJvXOuLsI=,iv:DknrQWbVTP/UISqz3BhpiY6Bump5BHAJ9OV0VZzzO6c=,tag:UM0+/LxcF6vbh9UD2r1lzA==,type:str]
    SECRET_BOOKSTACK_DATABASE_PASSWORD: ENC[AES256_GCM,data:UE1Slbc/Q0U=,iv:OQtL6MR8wrEcRaJUQKePJ0agrwTfmEdYCAlVruOuF1o=,tag:YqQ8sXwcEsfmaQX/4GORhA==,type:str]
    SECRET_VIKUNJA_POSTGRES_PASSWORD: ENC[AES256_GCM,data:Sp77LSNFuYo=,iv:1NXF57Jq9vZjFJ37XjpPbPB386uuUCEpXPEct6I8AJ0=,tag:kQKJCN2xsPjQVvw2yGKgGg==,type:str]
    SECRET_VIKUNJA_POSTGRES_ADMIN_PASSWORD: ENC[AES256_GCM,data:dCFsI3ss3tk=,iv:aMUccHpKQ4B1iW9YqH2hd4MNnxz5T1lkW5lgUSJ+IHE=,tag:zYOp3GZqPe3MPCOUaaxjog==,type:str]
    SECRET_VIKUNJA_DATABASE_PASSWORD: ENC[AES256_GCM,data:RTpHV8GiyM0=,iv:MOKudkIdgDVWf5q8qREi+6HrCgOsjsEcEMcwj0otg/s=,tag:WglxhlH1myJHEqL/Lw8hew==,type:str]
    SECRET_VIKUNJA_JWT_SECRET: ENC[AES256_GCM,data:+XO/m1BQ24s=,iv:443iLHvC09Rx4YzFGXxczWmltWnpK2oWyzEV9JksIhw=,tag:C9QV9CIJv56tN9wcHAHhzA==,type:str]
    SECRET_RANCHER_ADMIN_PASSWORD: ENC[AES256_GCM,data:SIyVqcGB+uU=,iv:bPeGp3sw7zxCbK6TL1HA2z5Pgw9D8xgUFNlaPk5HMvs=,tag:xyXkGVo5L04NZ9qn6v9G1g==,type:str]
    INFLUXDB_ADMIN_USER: ENC[AES256_GCM,data:0HCwILk=,iv:FZaEoZqpVxKHXj7wE60tOMSwRO6xbpmdGTHLVs/4Rzc=,tag:KRcGTGa1sGjzGeubEmJWtQ==,type:str]
    INFLUXDB_ADMIN_USER_PASSWORD: ENC[AES256_GCM,data:M9f1Qcz59y8=,iv:oVlfNNogyBM12iHgwJGxmASGWdJ4baV0UL0f0tS+ukM=,tag:atXuF9Z3PskQ2Ejvg1tTww==,type:str]
    INFLUXDB_ADMIN_USER_TOKEN: ENC[AES256_GCM,data:xsu4C9KbtytErA==,iv:Hz/GnDZQJquNs0v1x3nTSVzfBo387xGHSPWW8oD73dU=,tag:dXb/4iUwhdxiovzjLQ3gLA==,type:str]
    SABNZBD_API: ENC[AES256_GCM,data:0JyyOsh+JdMCsRjjAuw5ZQX1bLyzGj/MdL9DXljTzLI=,iv:6HXCujtOOBUW/FlFe1wQ2eeGeYh+/PcPu9ZqXnRUAN4=,tag:gkzlRnjH+x60j7vEOPDHLg==,type:str]
    PGADMIN_EMAIL: ENC[AES256_GCM,data:5Rsg0etE8UJfkEiUmmHVxw==,iv:WxeKFnIMRb9g3sNRsBUMjXLzyRXsSJL/RULBakAw6h4=,tag:bONaku+6E6d63DV0/UKjfg==,type:str]
    PGADMIN_PASSWORD: ENC[AES256_GCM,data:u2rbk3LGzTs=,iv:h1iMsweCDCdmxieJOfOEfSsKb9dTKEYC/vuL1yLaRMU=,tag:czYH7yCeLt9blPZMvZblMg==,type:str]
    AUTHENTIK_POSTGRES_PASSWORD: ENC[AES256_GCM,data:STU0PxAEGJHr3eNFINM/,iv:m6YYuYOc3Nyh+M365Wo89McFQLjOoCgFsayat3TPWmI=,tag:RlsVuQ5BpjqLngNUaldJoQ==,type:str]
    AUTHENTIK_ACCESS_KEY: ENC[AES256_GCM,data:Ws+j/P7xt8HCVvocwA/FPQ==,iv:iURaW9N+0WJja91ehyzxJjOu1tyfzrBDbjjJ20J7xqc=,tag:Ob6FB1poND9YVFcMdI8usg==,type:str]
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:CqoqIR83dUtLdO9W3//TpbVuTUf3+OBh922KPxtY178=,iv:U2eUtUUIgc4onLa2QWWAB2V/foxw2NH67AYPc5tGJMA=,tag:8EqFn1w+WYGf4+dYbV/8gA==,type:str]
    AUTHENTIK_BUKCET: ENC[AES256_GCM,data:e9qCV4fUIAqH,iv:b29QXKTy6DkIMdWZbkHu6qzYnRuklvcTQ8Oz0If/iik=,tag:9q/Q5XqA9U/XYUptB6E1MA==,type:str]
    SECRET_GRAFANA_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:MtXCKJRBUajzEScm+Q2PiYZbKpW3+Turaus=,iv:YDFs7JRIGs3SdjrSZ+Im9cUOoePmu5SpmO3aO5fuOV8=,tag:se7xYdU62U+YOYg89Ebrlw==,type:str]
    AUTHELIA_SMTP_PASS: ENC[AES256_GCM,data:2FjIk7v1Hm6JYimO6MXiCg==,iv:bIoxoebVgVH5KvZHLC5MZ+rVBY4YZ+ML8Vte1WC6kr0=,tag:iHqaInoJgVCkRMNkkQw3Vg==,type:str]
    SECRET_PUBLIC_DOMAIN: ENC[AES256_GCM,data:+gjYINFWnEN/5ao=,iv:AsWIrLmAmbuPtt7dFFwjoL46a4KmmOK5Slwlca5Rp18=,tag:HrYrJ4yaKyLyqHW+hP2jag==,type:str]
    SECRET_OUTLINE_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:7zYpO8hftx10Inen6Naldv4kT9IQMce6fbw=,iv:Xwq5ptDn9yylRO5mq7DAH7IN2KDGUsC+cXJlF588yxQ=,tag:StOgRlsDAes9iK1uARJvkQ==,type:str]
    OUTLINE_POSTGRES_PASS: ENC[AES256_GCM,data:OBDQsXUYXVA5twrXUpX6+yYw13wGeO2F7cE=,iv:MlvcCfGd2mMDK1rswhWFGxA754BtyAOPXulH9gvg/b8=,tag:RivLEqZLppGNzu5ECG6v5w==,type:str]
    OUTLINE_POSTGRES_USER: ENC[AES256_GCM,data:YZokGVd0Kg==,iv:2NFk7QQaXghflVD6TsAGm4v46MY1ap1UOBM4FppFxs4=,tag:he/UxZuQmNTeI+MsqTdZow==,type:str]
    SECRET_GITEA_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:KLB8AbXDSa8B8Xtmkz9fs83mGVJbIiBA5BI=,iv:aGsVYs07NEtMNB0YOcJoPJq5iLu8bWY4lHi3jy69rko=,tag:/JDkBH0NhCGQSqNBnUi0nA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL: ENC[AES256_GCM,data:skwCRudGJhGHLlTGb1DlkdfqYLbSdV+fKKklB8O9W9I4pPkZOuY3m+Lujtx4xHtE8601fBA=,iv:tvzGTRkdbp/M4X9SEqZJZ4NUoi5SJcLzae0thyI6BV8=,tag:MR7U/HGBk2TNtESSPP5Xkg==,type:str]
    HARDWARE_DOMAIN: ENC[AES256_GCM,data:ctxBlPxlA5imTw==,iv:2MT7l5AOIRjltIgrfLWF36jSHRL5dCLpEns+4B2LkPA=,tag:u9rmAAEfrYq/1krZq9evTw==,type:str]
    CLUSTER_NAME: ENC[AES256_GCM,data:fE+RplLHAw==,iv:pYLiSXIGhaLtmK7Xw1LYzaDqmOz6Lg8X8gjpEsQigAk=,tag:RO+yRJWWm3PCytrvLVLGzg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArTm9oQ2tYQVhIUHJGVGt6
            K1BCVzlMQVNhQzFSVEpsSVNJTXVwNlU5VWpFCjNGMFc5LzNNRFZZV2dHL0ExdndJ
            Q1BKU1NHSU5TWWJVaEdOUDhZclBLNTQKLS0tIDZRdXZlWkEvcGpOOFNFWnNyejA0
            YzJKd0xBaDArNVFkL3BDTE04c2twWlkKtrl0Gn0sE6ZAwpFp/sgP43DtngvB1w20
            mKdMnesSilA6+xiO50Rz51MHzEczW8rQ1RelhP8dhn5A1ZMi4M1BfA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-09T10:26:45Z"
    mac: ENC[AES256_GCM,data:CVtUo0/ttURsp31OvE1Dhmynf4LKf2+AqtruGtlNs4pjOJVOCpekrl7Sfbz9rhZ92aM/SvTid8mSSmvLjCaUOH5FgysV9hiN4fgQq3ilMAfbSgqvYpwDRctiOK4up2Acg4o2J1p1gnb1U5iS8xXIUs66ox9cpVSZeZaMTYYV/Z0=,iv:ntXnzY3qcxcvVsI6Hq4ttOCSO9Z+VMRyvn4C4OfRPFg=,tag:1dHBz5HURM5WA7rHQUw5Fg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
