# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: ""
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/secret-reflection-auto-namespaces: ""
stringData:
    SECRET_DOMAIN_LOCAL: ENC[AES256_GCM,data:zpm2iK5Ou4cpVTv9,iv:/xqbd9IfhEI5fdK+2jsQPYPrgrHNSq+kDhXmo+fll6Y=,tag:Il81FLAC1li1sxOZQMpkCg==,type:str]
    SECRET_DOMAIN_CC: ENC[AES256_GCM,data:VNsTvvdGBM/w7Q==,iv:JANDjNCVg0WXtWIeozG+jQIkkOB1qwbWbQQrMcDej74=,tag:hNHWRCuCblBLsBJuzujMTg==,type:str]
    SECRET_DOMAIN_CO: ENC[AES256_GCM,data:QGprcP2idpHQIQ==,iv:X1XFKlIsfyB/YlDZU4DtRSa1341aVMvNyOQiLqTK4d0=,tag:eHZOmQi9Cylau8wNsZYfUw==,type:str]
    SECRET_DOMAIN_TV: ENC[AES256_GCM,data:zgAKrlK6C+8+zw==,iv:QL85zUMIWRe9eQKEaT+v+BVFIL+R0ilZt98Y3rTuxIA=,tag:7FTH5Lqc3JlgJsoRNWAG6A==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:F2eWguUADuqk7lo=,iv:VPJx+IUCrU2OG0mjEoB0WUe/LUYg+4B93WHE9IAp2b4=,tag:4sa9tNtTnAfz1KRAktvNew==,type:str]
    AUTHELIA_SENDER: ENC[AES256_GCM,data:H587ZZWRz3wc8m1ceMlcjNbXYbhioZ3BBQw8,iv:6CgymyFv4bJJr99k+e1DSCF6wmALF3WuWMkqwbqD2RI=,tag:YBsZEQ8hC6SE6HXOCzQBTw==,type:str]
    SMTP_USER: ENC[AES256_GCM,data:MYsbouTKIDklMJbsO54SMQ==,iv:lIDDUAGMPMjcXUCcw7WgK9GN4uf+9+hSQR8IuCySTs0=,tag:re06aM8qGx6X1SIeksC+Pw==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:g/oa4XbWeWEoxD49wyR0wg==,iv:AezWINHLRWsOX+DZN47Y2JdzUrDdIATW7A059zGj20E=,tag:MhjCISUd967geIfb47gRYw==,type:str]
    SECRET_CERT: ENC[AES256_GCM,data:l4G2LtLeSZ91WWOVJDiKPUD8tJNuA7RLscs3Y0fBenUEzWsu98Hzgmof,iv:9lXVzRNYEcn9DB3ZTyh5liMDq/p3h8xA1/TmSbx/xnA=,tag:ChHl5ZhBXU7R2kFJgv5hEA==,type:str]
    TZ: ENC[AES256_GCM,data:CKzR7xuB3VGyHb6ua1m9xP9E3c0=,iv:R9F1844PQMIvD/BSmcSEHOp0CBA8J7fgk6j4ZaLmqTM=,tag:wJuS8pBqhPKzDn3pdOSbow==,type:str]
    NFS_SERVER: ENC[AES256_GCM,data:wTkNW3LJDlxbvc8=,iv:M6C9g5GzIYPfEWG5pY6gAiBybBEO8mpant/g/73Kuvk=,tag:NRAMBqJ8cPXqPuBunSOHwQ==,type:str]
    NFS_DOWNLOAD: ENC[AES256_GCM,data:JusdaY629kAHTuNZftirXBY=,iv:7ktkimJvp5I3l9VpQKdCgsjxjZfQFuawMmvU8fPfjSA=,tag:nXzH4bPprw3D+v5P388XEg==,type:str]
    NFS_MUSIC: ENC[AES256_GCM,data:MsS+ZatIzwb1LKI5b0I=,iv:EvglV0LynZHK5HOP/cMZSOkKkBmc1EN9eG7z9teLLjY=,tag:q1AhOLQeawLtq/pXjrRvvQ==,type:str]
    NFS_MEDIA: ENC[AES256_GCM,data:nmlvTG/HTJ00uDoCLVs=,iv:6XV+0W/ZcmWqZ3oam8M1weMT15G8yAX/ITxHRaU02z0=,tag:yH2kTqSVmfGfdvAdCVoU8g==,type:str]
    NFS_BOOKS: ENC[AES256_GCM,data:LQQr4quvnaaaHdbAsZ8=,iv:91iVhbgyjQCYQ0CODR2czrJ6VD4T1b15FHlt3nK6iQY=,tag:qfN8SyLa7nrdGb1gL6VdWA==,type:str]
    NFS_KUBERNETES: ENC[AES256_GCM,data:0Rf4/lYI7f6ez59j+xpkonNiEA==,iv:SJtmmdFKpyvtry3wMwz+AUbkEuYnTqo0VyVhBGnkwJg=,tag:ApV5zY2ML1yMoyVLDidrug==,type:str]
    NFS_CSI_VOL: ENC[AES256_GCM,data:j1KMjPEHO7VqGK8j7htq6Y473Q==,iv:0f8mGv2dIFYkB53wscgxzC/vyPbix6yZQuxUzYp5Dbk=,tag:3WV9Fmmsxv4l4lZtui8Few==,type:str]
    NFS_SUBDIR_VOL: ENC[AES256_GCM,data:b5whD1215IEm54SBHr8o5CSVvcoTZ6Y=,iv:dj2nKL9jTJ961D7jc6QE+WqOrDNTzgR85MlgQQj4T2s=,tag:KsNGSidwdhMmuI8+BVB8OA==,type:str]
    EMAIL: ENC[AES256_GCM,data:iGNRknRPGuAMWQ2B/qeYHg==,iv:QQzm0qoBnFtvP8FyZHNJxrwHETNU5sU7JnRjTZbIfJo=,tag:zvhrUc0jiBuq3B8Yq0MmVg==,type:str]
    HTPASSWD: ENC[AES256_GCM,data:DtXvswqFa4PJVdhtnnpUd1lt+pwnPC28n2qRCu8XxcfrXLsgwTa/byFewvxgCSI5fS/txJYivGZwhw8kddTkhByD,iv:8qIrSaY1wVZuVg+pp3tlW1iKqETiVtYHqWY5Z71i1MI=,tag:revclkFCtWRAJqRI1pe/ww==,type:str]
    TRAEFIK_IP: ENC[AES256_GCM,data:TZ3Y0B81cweIjSw=,iv:EOwj7pQuCnMTh8OKeKknvuWSYU+r5VNpxJVWmyVyU50=,tag:kMcGz9gfbaJjdgHJ3fxrdA==,type:str]
    LONGHORN_BACKUP: ENC[AES256_GCM,data:spBx3OiUBGqgY7Jbu5xMpUYPrvCVzftn5+NBTfTxHeywWrs=,iv:D4uuhbiCOyX3830N9Qaju7+CBMkU34CCcTxelJS/TdY=,tag:/GJtoo3L84OvMTk68MG9tg==,type:str]
    NFS_FIREFLY: ENC[AES256_GCM,data:MWa5+IDJuLCSZrWXJrF/Qg==,iv:LxK5+qbl7Wce4j4huaahsdmCdWdJYIUtbnDUxgL2sLY=,tag:aq5dHhpu3OcrDC6jqG2n3w==,type:str]
    NETWORK_K8S_CLUSTER_CIDR: ENC[AES256_GCM,data:lzlclk2EMTxL+tea,iv:s+kMVI9XAj/kXYmdHyc9Y0+Jhq4JmKsRsk1ZBosp6r8=,tag:tNDEUXD5G66ELKVBmhNxYA==,type:str]
    NETWORK_K8S_SERVICE_CIDR: ENC[AES256_GCM,data:at5i3J6unNsAIJaD,iv:Otzh6C0oC7/lgPpiEz9lYyxVHesjVgfFtihNJ7ttG0E=,tag:8BUrhfgLACOVAEXrTR5TEA==,type:str]
    SECRET_WIREGUARD_PORT: ENC[AES256_GCM,data:IWQ+WO0=,iv:oBW/1hk4UJeJhvZYnlskpKpuxBRIMzTw5yamx1RMXz4=,tag:zMZ0EKvdcJ/LlR04OIeYqA==,type:str]
    NETWORK_SERVER_CIDR: ENC[AES256_GCM,data:SUzKcdSFGlD73w==,iv:gosk/M2o2WJkaqe5/kezvLL2eFbQapOYMhZZ+yYYdNc=,tag:m3eOoEQ9CV4OGCZ0yqXIaw==,type:str]
    WORKSTATION_CIDR: ENC[AES256_GCM,data:4cBmO5S/hOTPvg3NhhU=,iv:egjnL+jPNlzMP6U4lvpDzxviX1tjz6Nqtl0GRX75pmY=,tag:01PB+YG+D3rgceV4gRplrA==,type:str]
    SECRET_PASSWORD: ENC[AES256_GCM,data:wVwwOloWP+g=,iv:yOxpLrhTz+imdTDLm1ThjP/rLGtVdSh7J2B80qXFSdM=,tag:BwYFMPNoBqdAqo5qzgBjmw==,type:str]
    SECRET_QB_USERNAME: ENC[AES256_GCM,data:fBjxFoE=,iv:5KMOUs0QqDFCX0hScpeRlkJPI9ScvcjmY3BnYRWghN4=,tag:nz32PQQd0lZ/i0KJkf7Mog==,type:str]
    SECRET_QB_PASSWORD: ENC[AES256_GCM,data:/pDo1w9KfTE=,iv:kFDKOUFXUYasZYwjJpE1yIe/OTlFiFHDdrIOzfKo3E0=,tag:Vh10DhUGaRcDCIFcgbVVhA==,type:str]
    NFS_MINIO: ENC[AES256_GCM,data:pc+VrJ2ZSj9pGzJdwlg=,iv:BtdStbOYGm3abWypyyA31Yr1wyR+7/fNGzaehTnKwd0=,tag:tfehS6dNbO1/rZdoq7TGlQ==,type:str]
    SECRET_MARIADB_ROOT_PASSWORD: ENC[AES256_GCM,data:xfpsaLYRBio=,iv:K8bOOY4w/tNjcItWomzspdTIQDfrdFwRvDR19nLFYDo=,tag:6h7VwnWxqFb2477jc68pJg==,type:str]
    SECRET_POSTGRESQL_ROOT_PASSWORD: ENC[AES256_GCM,data:uE1WroJP8Is=,iv:Ff3dAE1T/ItwdCGMu4m/KUcr3VfldzoNXLzg/eXujC0=,tag:eMpvaYDebfgUbqt2B1bybw==,type:str]
    SECRET_KOPIA_PASSWORD: ENC[AES256_GCM,data:ao76C0wqgi0=,iv:rHmgoQxRoDm1IRR4Rr7CHgDlMVgRRWCaVv8yFrhYvuA=,tag:g+gwFYlM+5+obOsfXcTJ2Q==,type:str]
    SECRET_BOOKSTACK_DATABASE_PASSWORD: ENC[AES256_GCM,data:TS6sSFtljXQ=,iv:eB+sAvwI+oMg1uXTTzQPf+OZZ5KV/M2yOk6hbiDMxzs=,tag:OMUoGn1dCW4E8L0Sil5CSg==,type:str]
    SECRET_VIKUNJA_POSTGRES_PASSWORD: ENC[AES256_GCM,data:1bzQlsPHz5U=,iv:hfgA1weUr8F/TfKJvAhuRIcTs5hJqf5D5tIouDZvIV4=,tag:YhENJ6dIxTVWuPLwTwrmow==,type:str]
    SECRET_VIKUNJA_POSTGRES_ADMIN_PASSWORD: ENC[AES256_GCM,data:UBevk3k+ge8=,iv:przcaSMGnVSIg3WjE/HYXbfSVvrhX/tCjg18KWEqoAk=,tag:rwGqn5pa7eallkZgg1dMOA==,type:str]
    SECRET_VIKUNJA_DATABASE_PASSWORD: ENC[AES256_GCM,data:DACzTAfC6FI=,iv:AHv6IdfWfZW/fhncqNbpKjc+L4ue8Y5PB1WEvKl/hf8=,tag:BTE6wVuELFDQxaLKay4XTA==,type:str]
    SECRET_VIKUNJA_JWT_SECRET: ENC[AES256_GCM,data:MeiqldFxJts=,iv:bDMm9JkCW11WEUf2rl8Yo1BovK9g8Qc2jYUUxu7aabw=,tag:9RGwgxoK43lOsm66KAD3MQ==,type:str]
    SECRET_RANCHER_ADMIN_PASSWORD: ENC[AES256_GCM,data:dNs2SrZTMFo=,iv:bZQqTbqbtXt0hk9yDM+VUrlWX6tXoWGOoUa1PDcp4w8=,tag:oHu/l5hpHSFuNOd5b9IYGg==,type:str]
    INFLUXDB_ADMIN_USER: ENC[AES256_GCM,data:o/mAoHc=,iv:IbuGY9kGQdgswFoS4bUmRcqz1iPlYpPBKZYcWv48lC4=,tag:0JZLL+9FXm875KOzH50PXA==,type:str]
    INFLUXDB_ADMIN_USER_PASSWORD: ENC[AES256_GCM,data:9lMdGGTu65o=,iv:So3JqKz+rt7xvsZF6F20qG98V+Er2LLd/NJsdqlNohY=,tag:CJE0RhuuZQ7GWcEAnTOeAQ==,type:str]
    INFLUXDB_ADMIN_USER_TOKEN: ENC[AES256_GCM,data:JXq7vBHtFCvPYg==,iv:gbiDrcPIfsIXu0IcoXJnbOPL3F9ctr3DVPdR9dwxDw8=,tag:WaIvtqwEuFEvsncVzrKdVQ==,type:str]
    SABNZBD_API: ENC[AES256_GCM,data:BOXgdWhvZcbxTzrJX761wto7rfnUnuxisHm3j2VG3+o=,iv:iG0tnFI5EsR2I6/u27y/1QaQGPrVxr6XotmLToLBeRk=,tag:rAStC4KEofUQZ9lswaBV6Q==,type:str]
    PGADMIN_EMAIL: ENC[AES256_GCM,data:SYbiEQgDF/qDnFC3Gk3+Ag==,iv:ASfhVUCtRYFJmIodYMPPRXCi34V7T8Fn4SF0U15l8fE=,tag:K+e502n35nk2xWkui56NWA==,type:str]
    PGADMIN_PASSWORD: ENC[AES256_GCM,data:cd2yVV6iceA=,iv:OFyQ1kTIxna5Q5qYI3G4LFzCNEb8MasL7ptyG8U6pZk=,tag:ttp9Tu64/crgeUfpsvV8GQ==,type:str]
    AUTHENTIK_POSTGRES_PASSWORD: ENC[AES256_GCM,data:uzzdW4lNjf8pjh1UYVN4,iv:vezX+4pE/1jVqBwYlmvsd9/USNlshpOjDejDTsTMGtI=,tag:eH9b8b6xk3sqzmVcTIVgjg==,type:str]
    AUTHENTIK_ACCESS_KEY: ENC[AES256_GCM,data:Eai4WZj/oq1pXk9U6ojFbQ==,iv:qsScqa3ZuLkgDyi4jvA3/MWrt4N9zIZ56n4FXegVn9w=,tag:ngnENZH1bKJE2OrSrYSn9A==,type:str]
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:AvTPBJXfApkTHBvfeCvPEOOc4NTvrnr3ApGTbJhQlbo=,iv:hzHLhNI+Ws1DWTtKH6OS66WMC8Ym1de0XCQB5t8UfNE=,tag:9GMBFj+G3cOn6R8k2G3fSw==,type:str]
    AUTHENTIK_BUKCET: ENC[AES256_GCM,data:uC50UIKDrwPD,iv:6m5N3fLyQV69lyiQqMukmpt0JM17Z2+8PRmaEvrHsKY=,tag:G2qKJE2v2nz3jvJgL6xe5A==,type:str]
    SECRET_GRAFANA_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:MeB+LGdVIpu54JJVyYPuzL9Kra02la13IyI=,iv:ZuwK/QaBj22Fr9rpJgSD1dB0d4rqXoxRRlNO4Sgr5VQ=,tag:Z3pI2qBhLfP30h0nNuJz/A==,type:str]
    AUTHELIA_SMTP_PASS: ENC[AES256_GCM,data:OdUOeWu5HpYz7ZTPWZS6Bg==,iv:MTHZALN/h9Ge3zJ0opZu3qi/ZXUhqgPMffeWNaEGr0I=,tag:iOGLX9kIa7kDv59TgqNmIA==,type:str]
    SECRET_PUBLIC_DOMAIN: ENC[AES256_GCM,data:kRhKjVy0aSd5h8k=,iv:jJYB2Dw0bYPDXWcRcE1VoexQS+KqEA/pensLCNFIbFE=,tag:sPKpVc/0C2iiCL0CZt7jFg==,type:str]
    SECRET_OUTLINE_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:df7qtT7/tTPZ6YJ4y0O2BoCEvfNTraOUKjU=,iv:dvytu0vIerPF6lf3D7QCtr+d+PTxo+N7FYBvic8zil8=,tag:Ia+BYIExpqAqRaEV0Wpvcg==,type:str]
    OUTLINE_POSTGRES_PASS: ENC[AES256_GCM,data:nLSMyTtoZu/FCW328LE4mZO0bXZ2rgwT7uI=,iv:zje9xxhrgGfRZgIx/Osj8d4Gs6FxzEpkJGYfxE2FO20=,tag:5rMeNFRxgOqrWl/lwE8t8Q==,type:str]
    OUTLINE_POSTGRES_USER: ENC[AES256_GCM,data:WeeqDorpMQ==,iv:mf5CVZ2CsDZnTULyPNcgb03ozdrn8BMhFk5+ENIZJB8=,tag:PN4B+ojfMydedhhbcI5DhQ==,type:str]
    SECRET_GITEA_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:6uikbvanMvjzGLKkpG2+nIiaZtu7Xh1pFjo=,iv:3CNPJaKIpxGKqn9RJNpkWh2uHz2CI33C1oZEO0bBcug=,tag:SOyrp0UHcg+TWC/9d25Org==,type:str]
    SECRET_CLOUDFLARE_TUNNEL: ENC[AES256_GCM,data:V61ZYA4NppmGjgcpXmjJvG9n11glH5xQ4Im8SfxFifkTvsLTmOPbM54mFpkojWXnZKlE3ow=,iv:cfKAX6vVRuq7JPDk927DBBSQGJFqkCJFrs6hLxCvccM=,tag:4JTzxXKvoWSUxDT+Hts6Yw==,type:str]
    HARDWARE_DOMAIN: ENC[AES256_GCM,data:k2xtFvIT+EvxhQ==,iv:TFYejvLMtfPVJfezAy+Pp5AuG5zNradgk53RlS7Cbac=,tag:MJiW9Ef0OJ4luGbjoSBEZg==,type:str]
    CLUSTER_NAME: ENC[AES256_GCM,data:hXuFbHBs9Q==,iv:W5GyyJGclvgkZlPV2mrSMmeoMgzE44VuIIG8o2cdzDQ=,tag:rBn75vHpr4WEQNsCzDCtnQ==,type:str]
    VNC_USER: ENC[AES256_GCM,data:CIg9xt4=,iv:9HDGCdyaB3bRE18NdywKypZptCmsKOviW1nkgD3O/5I=,tag:3WFGA0cP30PBDTecVrOh0g==,type:str]
    VNC_PASSWORD: ENC[AES256_GCM,data:iyHrp6hw4SU=,iv:OHtuYdSk2QXYQfl2usM3+jroSHH0Z5ce9k/ajHqe82U=,tag:5AW5TdzR6CMh6rFK6VXxTg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXU1VXT0p0NUR1d3F4V0Zj
            MGt0T2crRGMyNmY1SVpNbElzZ0M2TkZuUHhvCnp3RUw3QVlmb21HYW4yV3VVbHFQ
            ZjVkNEUyelBtZ25mSzZjaFVWNEpOYlUKLS0tIHRWL3NaUG5DaUlkY1pQZUkxYUNO
            Nzc1K3h3UDRRSk1YbWV3empRenFOYjQKyixUcLFnQDgwgqY5cxQ+q+QiP4OrkQ2d
            xW5TE7bDF/qxB4Cd0FFf69rWUbmdgfenNgAjPjKGG1VVMkyY6mqxaQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-20T06:42:26Z"
    mac: ENC[AES256_GCM,data:tgNONll8sNeLdZL2IR5CIqoxkv4nbTxuMQO3JnPefurzozzKLebAeoSdUcmMHktJjAwE/sTMCiBejJCexqy5+LXXbTuB0QuizEs1D/h+wNtEWDpBHlXHczpLYcfo1Yvd5vtKVnZk68U6A6AVg0KW1v2CMsRlmov+4Qe8fiJkbFc=,iv:8GbZ2uHY5N3RV7ycB//qeZlXlh2Pk1jdfUVWoMX3vkg=,tag:f0nMUm6mzxyg8HmM/t13Cg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
