---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uptime-config-v1
  namespace: monitoring
  labels:
    app.kubernetes.io/name: &name uptime
    app.kubernetes.io/instance: *name
    snapshot.home.arpa/enabled: "true"
spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 5Gi

  storageClassName: longhorn
