apiVersion: v1
kind: Secret
metadata:
    name: wireguard
    namespace: wireguard
type: Opaque
stringData:
    wg0.conf.template: ENC[AES256_GCM,data:Y7vO4gWbUHXie3BCsp5j2AbopQGoaKWX47nQd0JDNg/snHTlHf7jmOX5J5yuu0Aa6x402FW+V1pWnwgQEBdUBZFoi1Q68TLNaq1iRKtAhVpWtrILoIzds0eG005uDxFeXcG3UvWITuLoIP94QOAV6XFDetgscN9LaT5tRodTQWT31lKW/3c+q1wH9AGw8Va/puEpUTg5VTJ9y/Bh3ftWNK6MfkqwWV+fVF9zMVtsn/vgI87r9FnCdEDM1S5Itwurqfd8/kaJ4ckp4fIK4ps34LebO0Wo2g2gS4le4qIYeSsTdlH+d/tPF0ECN8Ds7ArKBL5ZqOISfLSHxH2U3xUCBEF2nL86N1NO+GhMI3vE8CjmAQa6AH5WM7xjNk0SPDGzsmEVdWHWeRfhpwQExq4OxkbfprXeTXbxxuNL5mjmThJCkfkBIqKRCppvnStfNMS2vGlRSTPVrfKD/SKlG8NGmuaJjNEqXSS1ITjeCPbbRt/xfwV5JXD0UvI8OPo5D/69uX4CsrmLLe8R8D7WYe3vpZecgZp1uFRgsJPx/jaXKRNaGwHqTWGo35JSkJeP4o4Ru3TZ9jaMJBs46Ur6wPes3Y/D0Z5BTSwhWEWkUdpxBKC4JcQNriYj+z7J9Hl0gYAsRmtJAOSyyaehL6HFbk/ZhcJfRSCTnzraafbcWMTk3RMzTaHiA3ErbwyxUKWkSNuBKqL5udHX53l7NbGAmGFcjQvvD1nSySGfPwa/azUaUXb5bkB4UcC9nqoFF/jLK8t/zoxzV86LUcv12iUSYN3+JDF3J/Eg//jHpONAKwftExnAmEX6LZR0qGXE1ufUPKzvUgF/zD+zm1z9BrshyhclGGug8J+S,iv:ukYxaaR/fQSg2uh7xGX1f23sbjrjv9p/3yUYJ+np84A=,tag:giAOleoeXzajuY8CxHXbLg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4bUVuaStZNWM1c2F4WmZC
            WlpoM2V5SCsvZEVkUHVJa05FOHVYSC8yYmpvCjNjdVl0NkF4dlZaa3NrUENsdFYr
            b3A0anRsRmh6V0hHWTVra1YwNjF0bHMKLS0tIFVDQmdKU3d4K2lFYW10RE9WU1Ur
            OElDZnhhQWttTDUveElHOWUza0pwRHcKbhEjNgLLPsmH6AY2Wj0JHml8dsqLCTZj
            Do1LnqweXxrWdwX1b4IPmZSIXKBLXEA6b10esRmeFTr8RkYDIjeLuA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-10T16:54:28Z"
    mac: ENC[AES256_GCM,data:0dPwcbLS5TE7iRWv8Dwv3qx6OWI/9MPhJQFST79PPz5ZoB4j5EPDH+wlaiHCHsFRmY/QIXCvIMPz7gyVmV+IF0dHj8PwNoN78/wKi1eprtFi+kb5bpnjJ7q5sjc+hC27+GwSM1Hmfndf0S0gldrLa8ni7g1Wl31DDTYox6NvU/o=,iv:D8UFyvCSo8QD12z45iWhY20fOExH38m6PhNsrES2Bk0=,tag:WvsXWMtseOlYyGLXjvAHSw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
