---
apiVersion: v1
kind: Service
metadata:
  name: wireguard
  namespace: wireguard
spec:
  type: LoadBalancer
  loadBalancerIP: ${METALLB_WIREGUARD_ADDR}
  externalIP: ${METALLB_WIREGUARD_ADDR}
  ports:
    - name: wireguard
      port: 51820
      protocol: UDP
      targetPort: 51820
  selector:
    name: wireguard
