---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app calibre
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.2.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      repository: ghcr.io/linuxserver/calibre
      tag: version-v6.8.0

    env:
      TZ: "${TZ}"
      PUID: "568"
      PGID: "1000"

    service:
      main:
        ports:
          http:
            port: 8080
      webserver:
        enabled: true
        ports:
          webserver:
            enabled: true
            port: 8081
            protocol: TCP
            targetPort: 8081
        type: ClusterIP

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          hajimari.io/enable: "true"
          hajimari.io/icon: "book-open-page-variant"
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: "calibre-tls"
    persistence:
      config:
        enabled: true
        existingClaim: calibre-config-v1
      media:
        enabled: true
        type: nfs
        server: ${NFS_SERVER}
        path: /volume1/books/
        mountPath: /media

    resources:
      requests:
        cpu: 15m
        memory: 249M
      limits:
        memory: 4000M

    probes:
      startup:
        spec:
          initialDelaySeconds: 60
          failureThreshold: 160
