---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mariadb
  namespace: database
  labels:
    velero.io/schedule: daily
spec:
  interval: 5m
  chart:
    spec:
      chart: mariadb
      version: 11.4.2
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  dependsOn:
    - name: metallb
      namespace: networking
  values:
    auth:
      rootPassword: "${SECRET_MARIADB_ROOT_PASSWORD}"
      database: ""
      username: ""
      password: ""
      service:
        type: LoadBalancer
        clusterIP: "${LB_MARIADB_IP}"
        externalTrafficPolicy: Local
    primary:
      persistence:
        enabled: true
        existingClaim: mariadb-v1
    resources:
      requests:
        cpu: 15m
        memory: 105M
      limits:
        memory: 105M
    podAnnotations:
      backup.velero.io/backup-volumes: mariadb-v1
