# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:zO+TyV/TnrOnsCf+ckPDVHmPTaWiiTk/H+QsCblH7EIn2Vu98g==,iv:UDyrXtnKKxK3PV5tTLwDlVj8lA3cMAnbtEuZtYwK8yQ=,tag:GIF7MP/BF+kRToY2TuroBg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEcHorSnk0TXV3R043cjEr
            SzRNMDRHejZ1czZpVG5KT2dOZ29POWs2VlVVCnQrREcwYm43UjFWNGsraTBRdlBB
            K2haSjZtMGhpWXI2ZSt2WXFrYllyK00KLS0tIGV2V25GdzdteDlRd3o4OVU3SDhs
            WVdDVDNXZ1UyaWpSN2VGK2kyZGpmQWsK3syfKCvrBHSV4SnjRujYIzh5Rt5bCMLK
            qmyax8JMgeNozkeD+yUSfxNurszIRvWN6OMafL5Fn6g39jfdH6dS2Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-26T16:56:20Z"
    mac: ENC[AES256_GCM,data:xGKnMnmpUJbQ3v2+EoStQRHlBvUn1iMarNvyfctJcXOYFpmLtH0vkc3ngjxCaDjpwAWgrgl43xfb/lz+JLTZ9azdmob7unRJvI3zQEnK3uiT9mAH3Pn0t67nyEoP0knaUnp1S1U23hHZQoocHTDuu7JrETIg2t+frXshxlgxfJE=,iv:lfqGRESUQXP2Gm4dA/G1vi1vjSOEz7S+uf9lT42jAsk=,tag:w3mcV04RDkXv3+ijrYdEwA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
