---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./sonarr.yaml
configMapGenerator:
  - name: sonarr-dashboard
    namespace: monitoring
    files:
      - sonarr-dashboard.json=dashboard.json
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
    grafana_folder: media
  labels:
    grafana_dashboard: "true"
