---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
driver: driver.longhorn.io
metadata:
  annotations:
    velero.io/csi-volumesnapshot-class: "false"
    snapshot.storage.kubernetes.io/is-default-class: "false"
  name: longhorn-snapclass
  namespace: longhorn-system
deletionPolicy: Retain
