---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nzbhydra2-config-v1
  namespace: organizers
  labels:
    app.kubernetes.io/name: &name nzbhydra2
    app.kubernetes.io/instance: *name
    snapshot.home.arpa/enabled: "true"
spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 10Gi

  storageClassName: longhorn
