# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: monitoring
stringData:
    ALERT_MANAGER_DISCORD_WEBHOOK: ENC[AES256_GCM,data:m0o5FHcaHz4t/kq+jf0z/j0a5PLwEr3loHUJ+JQykZxwhp1YuqTAK7CSKKxa+/qrwBdSgkLA8ASoLSXZf+vFLct9ga/EuOjxHhDuUvpmp8JdmPgh/yMMyHptHbQFkiV1aat+4JH2oTZFI6tZhQcIqo0nFEYEZSuDUtFpHnZ2jw==,iv:OTkO5P4i5qCr3PdcHHS1SUzcdVAtwFs/NXfHeC7J7O4=,tag:qFl03n7bVn9vUWMD7JQq6g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTSitNMEN3WnZTUysrWm1S
            Q3plWmQvYXV5RGJDWkFlOHdvS2R3Z3Rqa2xrCkpyTnBQOVpHaTFkeVJhYVJMR1J0
            UXdkamNhamhpaXozYUdpcndvSHkzck0KLS0tIDBaQlkvUFBJVEk4VlJuVkc5c0R5
            R01ycmt3TUV3S0FpaHhEdlZ2WW1MdVEKha6r5+gJC/NgbrnDqJr2pvjrHP4K26Tq
            8HFJep0INIzGaZXCtdsxQiom5u+sg//DEZ8TNxA7O3Mu3UKUoQWFHA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-29T08:56:12Z"
    mac: ENC[AES256_GCM,data:befLoR6jUJC4BP3U96w+EgEC1i+I0cxq0vc39GXt4L0Lvz3Pdl27inaFnTPxdaehIiygaVrJU5hC9xQyePw1BfVKovJoOfNYqETraGoyyGLAUzNSPlDujPddSPQwqRg1n87ETB08gA53Iq81Pjdwdt2vSjd0AmcvOQe0kcIPlvQ=,iv:HeVmUbVJ+ktRb6sKpg80n5P/f3XQtZC4FiCaoeWm9Is=,tag:ZKhkYjIhADevlESj3wWuoA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
