---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: chronograf
  namespace: database
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://helm.influxdata.com/
      chart: chronograf
      version: 1.2.5
      sourceRef:
        kind: HelmRepository
        name: influxdata-charts
        namespace: flux-system
      interval: 5m
  install:
    timeout: 10m
    remediation:
      retries: 3
  upgrade:
    timeout: 10m
    remediation:
      retries: 3
      remediateLastFailure: true
    cleanupOnFail: true
  rollback:
    timeout: 10m
    recreate: true
    cleanupOnFail: true
  dependsOn:
    - name: ingress-nginx
      namespace: nginx
    - name: influxdb
      namespace: database
  values:
    image:
      repository: "chronograf"
      tag: 1.10.0
      pullPolicy: IfNotPresent
    service:
      replicas: 1
      type: ClusterIP
    persistence:
      enabled: false
      accessMode: ReadWriteOnce
      existingClaim: chronograf-config-v1
    startupProbe:
      enabled: true
    ingress:
      enabled: true
      tls: true
      secretName: "chronograf-tls"
      hostname: chronograf.${SECRET_DOMAIN}
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-production"
        kubernetes.io/ingress.class: "nginx"
        nginx.ingress.kubernetes.io/whitelist-source-range: 10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
      path: /
    updateStrategy:
      type: RollingUpdate
    influxdb:
      existingSecret: influxdb-auth
