---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./lidarr.yaml
configMapGenerator:
  - name: lidarr-dashboard
    namespace: monitoring
    files:
      - lidarr-dashboard.json=dashboard.json
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
    grafana_folder: Media
  labels:
    grafana_dashboard: "true"
