---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-config-v1
  namespace: database
  labels:
    app.kubernetes.io/name: &name postgresql
    app.kubernetes.io/instance: *name
    snapshot.home.arpa/enabled: "true"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 40Gi
