---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgresql
  namespace: database
  labels:
    velero.io/schedule: daily
spec:
  interval: 5m
  chart:
    spec:
      chart: postgresql
      version: 12.1.5
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation: # perform remediation when helm install fails
      retries: 3
  upgrade:
    remediation: # perform remediation when helm upgrade fails
      retries: 3
      remediateLastFailure: true # remediate the last failure, when no retries remain
    cleanupOnFail: true
  dependsOn:
    - name: metallb
      namespace: networking
  # values yaml: https://github.com/bitnami/charts/blob/master/bitnami/postgresql/values.yaml
  values:
    primary:
      extendedConfiguration: |
        shared_buffers = 256MB
        max_wal_size = 2048
        min_wal_size = 160

      persistence:
        enabled: true
        existingClaim: postgresql-config-v1

      service:
        type: LoadBalancer
        annotations:
          metallb.universe.tf/loadBalancerIPs: "${METALLB_POSTGRES_ADDR}"

    podAnnotations:
      backup.velero.io/backup-volumes: postgresql-v1

    resources:
      requests:
        cpu: 15m
        memory: 105M
      limits:
        memory: 105M
