---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app home-assistant
  namespace: home-automation
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.2.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  dependsOn:
    - name: postgres
      namespace: database
    - name: ingress-nginx
      namespace: nginx
 # - name: emqx
    # namespace: home-automation
  values:
    image:
      repository: ghcr.io/onedr0p/home-assistant
      tag: 2022.12.4@sha256:514b86674380400db8ff198a711b7022fac59fb346e643044c7addc67b326ac2
      pullPolicy: IfNotPresent
    env:
      TZ: "${TZ}"

    envFrom:
      - secretRef:
          name: *app

    service:
      main:
        ports:
          http:
            port: 8123

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          auth.home.arpa/enabled: "true"
          external-dns.home.arpa/enabled: "true"
          external-dns/is-public: "true"
          hajimari.io/enable: "true"
        hosts:
          - host: &host "hass.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: "hass-tls"

    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"

    persistence:
      config:
        enabled: true
        existingClaim: home-assistant-config-v1

    addons:
      codeserver:
        enabled: true
        image:
          repository: ghcr.io/coder/code-server
          tag: 4.9.0
        env:
          TZ: "${TZ}"
        workingDir: "/config"
        args:
          - --auth
          - "none"
          - --user-data-dir
          - "/config/.vscode"
          - --extensions-dir
          - "/config/.vscode"
        ingress:
          enabled: true
          ingressClassName: "nginx"
          hosts:
            - host: &host "hass-code.${SECRET_DOMAIN}"
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - hosts:
                - *host
              secretName: hasscode-tls
        resources:
          requests:
            cpu: 22m
            memory: 272M
          limits:
            cpu: 45m
            memory: 386M
        volumeMounts:
          - name: config
            mountPath: /config

    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: false

    resources:
      requests:
        cpu: 23m
        memory: 272M
      limits:
        memory: 386M
