---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app home-assistant
  namespace: home-automation
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.1.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  dependsOn:
    - name: postgres
      namespace: database
    - name: ingress-nginx
      namespace: nginx
 # - name: emqx
    # namespace: home-automation
  values:
    image:
      repository: ghcr.io/onedr0p/home-assistant
      tag: 2022.11.4@sha256:835ea67fbfd26041f8e62b8f2429c332a5ed56d270d92aa4357871a393e4e138
      pullPolicy: IfNotPresent
    env:
      TZ: "${TZ}"

    envFrom:
      - secretRef:
          name: *app

    service:
      main:
        ports:
          http:
            port: 8123

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          hajimari.io/enable: "true"
          nginx.ingress.kubernetes.io/whitelist-source-range: 10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
        hosts:
          - host: &host "hass.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: "hass-tls"

    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"

    persistence:
      config:
        enabled: true
        existingClaim: home-assistant-config-v1

    addons:
      codeserver:
        enabled: true
        image:
          repository: ghcr.io/coder/code-server
          tag: 4.8.3
        env:
          TZ: "${TZ}"
        workingDir: "/config"
        args:
          - --auth
          - "none"
          - --user-data-dir
          - "/config/.vscode"
          - --extensions-dir
          - "/config/.vscode"
        ingress:
          enabled: true
          ingressClassName: "nginx"
          annotations:
            nginx.ingress.kubernetes.io/whitelist-source-range: 10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
          hosts:
            - host: &host "hass-code.${SECRET_DOMAIN}"
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - hosts:
                - *host
              secretName: ${SECRET_CERT}
        resources:
          requests:
            cpu: 22m
            memory: 272M
          limits:
            cpu: 45m
            memory: 386M
        volumeMounts:
          - name: config
            mountPath: /config

    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: false

    resources:
      requests:
        cpu: 23m
        memory: 272M
      limits:
        memory: 386M
