apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: postgres-superuser
    namespace: database
stringData:
    username: ENC[AES256_GCM,data:HL87YyoNqGs=,iv:42SHQ0I32hd4GtnkcMp0PCvPKwJ0YtZFRAGnJ4pAupo=,tag:mq7ix4JBjxBxBrD8ZoTwvQ==,type:str]
    password: ENC[AES256_GCM,data:ZWORCEu38QI=,iv:E2fiuEcw2W7vN4vXqy2lVvLCO5J80jSFkbZBqSKmowQ=,tag:STbiZspTioEWR7OZuGikTg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1OWswbXdIQ1B0QUdxaVRr
            Ly85UUUzbHJLM2I4QnZzUjBTMWNYcFNjTFdzClhzeWR5T0xkUFVBcFRmUTVvKzhL
            TlZCay9ZSjVZTGJ4eEVlMUIvQ2Voa1UKLS0tIG1lZnMzNDVOU00rRTVoclpOaWk0
            bkpMYTRCdGIzSzRBYzAzZjdRcCswWncKF+d/AZeW84trY+gRZ/LzViDZ260V4MPf
            Nl7YI+8i2MsFasPEw7+eXuZ/+4RerqmCpJYPS9+XKOgm4OOohwMDmA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-03T06:28:34Z"
    mac: ENC[AES256_GCM,data:oW7GtP02K9vXfyYH5bhWoc+K0QfpyFUC3qXyn+W7BLZG6pTzldd+Z9hnL0QOfRuJZrSyxocRn3vTpjK5yhoqABycV3ffjdSl101nSCDENceMzBspB+2KI0+BZ9IaCbS/gV0B7LLgH4GbvWwvU/FFOtqIrkrvxv/fxNRpOktyZuM=,iv:6ITZ/uCJ6qkTb6NnprIpbDYffLXHafGYLpNZtf5JLm0=,tag:LhvrjOyoMkzTgN19+iwvmQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: postgres-minio
    namespace: database
    labels:
        k8s.enterprisedb.io/reload: "true"
stringData:
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:lAAWc9BBW1JXqVDl8HE7Sg==,iv:ILeuUQlfgUkcRLet/9Z74Mc1d2pd7VQ71ZnWwDXxFwA=,tag:g6SuART0NBeO18j3u0Y7hg==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:HHbSMOW/iB8sDvA4+N1GzqZ1k3quAvCmlCYpSSBOvFM=,iv:6zUzOG2fOFwE9O6Go1qpo0amRpjSr/gVtks0k2wkTSg=,tag:R8NWJnxyMkIBef0XTOV7Mw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1OWswbXdIQ1B0QUdxaVRr
            Ly85UUUzbHJLM2I4QnZzUjBTMWNYcFNjTFdzClhzeWR5T0xkUFVBcFRmUTVvKzhL
            TlZCay9ZSjVZTGJ4eEVlMUIvQ2Voa1UKLS0tIG1lZnMzNDVOU00rRTVoclpOaWk0
            bkpMYTRCdGIzSzRBYzAzZjdRcCswWncKF+d/AZeW84trY+gRZ/LzViDZ260V4MPf
            Nl7YI+8i2MsFasPEw7+eXuZ/+4RerqmCpJYPS9+XKOgm4OOohwMDmA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-03T06:28:34Z"
    mac: ENC[AES256_GCM,data:oW7GtP02K9vXfyYH5bhWoc+K0QfpyFUC3qXyn+W7BLZG6pTzldd+Z9hnL0QOfRuJZrSyxocRn3vTpjK5yhoqABycV3ffjdSl101nSCDENceMzBspB+2KI0+BZ9IaCbS/gV0B7LLgH4GbvWwvU/FFOtqIrkrvxv/fxNRpOktyZuM=,iv:6ITZ/uCJ6qkTb6NnprIpbDYffLXHafGYLpNZtf5JLm0=,tag:LhvrjOyoMkzTgN19+iwvmQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
