---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rdesktop
  namespace: downloads
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.1.3
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  dependsOn:
    - name: ingress-nginx
      namespace: nginx
    - name: downloads-gateway
      namespace: vpn
  values:
    labels:
      setGateway: "false"
    env:
      PUID: 1000
      PGID: 1000
    image:
      pullPolicy: IfNotPresent
      repository: linuxserver/rdesktop
      tag: ubuntu-xfce
    persistence:
      config:
        enabled: true
        mountPath: /config
        existingClaim: rdesktop-config-v1
      pathvarrundocker-sock:
        enabled: false
        mountPath: /var/run/docker.sock
    podSecurityContext:
      runAsGroup: 0
      runAsUser: 0
    privileged: true
    seccomp:
      enabled: false
    securityContext:
      readOnlyRootFilesystem: false
      runAsNonRoot: false
    service:
      main:
        ports:
          http:
            port: 3389
            protocol: TCP
