---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bookstack
  namespace: documentation
spec:
  dependsOn:
    - name: mariadb
      namespace: database
    - name: ingress-nginx
      namespace: nginx
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.1.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 15m
  values:
    image:
      repository: ghcr.io/linuxserver/bookstack
      pullPolicy: IfNotPresent
      tag: "version-v22.03.1"
    env:
      TZ: ${TIMEZONE}
      APP_URL: "https://bookstack.${SECRET_DOMAIN}"
      DB_HOST: mariadb.database.svc:3306
      DB_DATABASE: bookstack
      DB_USERNAME: bookstack
      DB_PASSWORD: ${SECRET_BOOKSTACK_DATABASE_PASSWORD}
    service:
      main:
        ports:
          http:
            port: 80
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "books"
          nginx.ingress.kubernetes.io/whitelist-source-range: 10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
        hosts:
          - host: &host "bookstack.${SECRET_DOMAIN}"
            paths:
              - path: /
                type: Prefix
        tls:
          - hosts:
              - *host
            secretName: ${SECRET_CERT}
    persistence:
      config:
        enabled: true
        mountPath: /config
        existingClaim: bookstack-config-v1
    podAnnotations:
      backup.velero.io/backup-volumes: bookstack-config-v1
    resources:
      requests:
        memory: 105M
      limits:
        memory: 2417M